### ISSUE TITLE
Prevent sorting of parameters

### ISSUE THREAD

**Issue by BenjaminBorn** [TuringLang/MCMCChains.jl#110]
It seems that when I construct a Chains object and additionally pass a vector of parameter names, the parameters in the object are sorted according to their names. Is there a way to prevent this sorting and keep the parameters in the order in which they were passed to the constructor?

Thanks for your help! Greatly appreciate the package.

**Comment by cpfiffer** [comment]
Currently, there isn't a way to prevent sorting. I can add this though, but it may take a bit. Would a keyword argument on all the stat functions and constructors like `sorted = false` work for you?

**Comment by BenjaminBorn** [comment]
Yes, a keyword argument would be perfect. Thanks a lot!

**Comment by cpfiffer** [comment]
Fixed with #120. It'll be on the master branch for a bit until I make a new release.

**Comment by BenjaminBorn** [comment]
Great. Thanks!

**Comment by cpfiffer** [comment]
Sorry this took so long, I appreciate your comments on this issue -- I probably would never have fixed this without your perspective.

**Comment by BenjaminBorn** [comment]
Sorry to bother you again, but unfortunately I can't get this to work.

I checked out the master branch
```julia
julia> Pkg.status("MCMCChains")
    Status `~/.julia/environments/v1.1/Project.toml`
  [c7f686f2] MCMCChains v0.3.11 #master (https://github.com/TuringLang/MCMCChains.jl.git)
```
but the `sorted=false` keyword seems to be ignored.

Minimum working example:
```julia
using MCMCChains

# Define the experiment
n_iter = 500;
n_name = 3;
n_chain = 2;

# experiment results
val = randn(n_iter, n_name, n_chain) .+ [1, 2, 3]';
val = hcat(val, rand(1:2, n_iter, 1, n_chain));

# construct a Chains object
chn1 = Chains(val)
chn2 = Chains(val, ["d", "a", "b", "c"])
chn3 = Chains(val, ["d", "a", "b", "c"], sorted=false)
```

`chn3` looks like this
```
Object of type Chains, with data of type 500×4×2 Array{Float64,3}

Iterations        = 1:500
Thinning interval = 1
Chains            = 1, 2
Samples per chain = 500
parameters        = d, a, b, c

2-element Array{ChainDataFrame,1}

Summary Statistics

│ Row │ parameters │ mean    │ std      │ naive_se  │ mcse      │ ess     │ r_hat    │
│     │ Symbol     │ Float64 │ Float64  │ Float64   │ Float64   │ Any     │ Any      │
├─────┼────────────┼─────────┼──────────┼───────────┼───────────┼─────────┼──────────┤
│ 1   │ a          │ 2.01609 │ 1.03789  │ 0.0328211 │ 0.0325872 │ 804.627 │ 1.00093  │
│ 2   │ b          │ 3.0569  │ 0.993089 │ 0.0314042 │ 0.0274476 │ 852.319 │ 0.999258 │
│ 3   │ c          │ 1.505   │ 0.500225 │ 0.0158185 │ 0.0101379 │ 1000.0  │ 0.99873  │
│ 4   │ d          │ 1.00577 │ 1.02307  │ 0.0323524 │ 0.0351559 │ 882.388 │ 0.999908 │

Quantiles

│ Row │ parameters │ 2.5%      │ 25.0%   │ 50.0%    │ 75.0%   │ 97.5%   │
│     │ Symbol     │ Float64   │ Float64 │ Float64  │ Float64 │ Float64 │
├─────┼────────────┼───────────┼─────────┼──────────┼─────────┼─────────┤
│ 1   │ a          │ 0.0454317 │ 1.26786 │ 2.01108  │ 2.75695 │ 3.9519  │
│ 2   │ b          │ 1.15372   │ 2.38174 │ 3.07687  │ 3.70836 │ 4.9824  │
│ 3   │ c          │ 1.0       │ 1.0     │ 2.0      │ 2.0     │ 2.0     │
│ 4   │ d          │ -0.977236 │ 0.332   │ 0.981136 │ 1.68844 │ 2.95986 │
```
so it still got sorted by parameter name. Any idea what I'm doing wrong?

**Comment by cpfiffer** [comment]
Yeah, you found a bug. My tests didn't actually check the display output, so I didn't catch this. I've opened a PR #123 to fix this.

**Comment by BenjaminBorn** [comment]
Thanks for the quick reply. It works now!
