### ISSUE TITLE
Is ESS capped at the number of samples?

### ISSUE THREAD

**Issue by goedman** [TuringLang/MCMCChains.jl#112]
Hi Cameron,

In doing some mcmc benchmarking work we (Chris and I) noticed that ESS is never greater than the number of samples. This can happen if anticorrelation is present. We've looked at the code but can't find a trivial constraint like that. Any idea why this might be the case?

A link to the benchmarking [work](https://github.com/StatisticalRethinkingJulia/MCMCBenchmarks.jl/issues/22).

Thanks,
Rob

**Comment by benelsen** [comment]
I think there's an implicit constraint in [src/stats.jl#L340-L354](https://github.com/TuringLang/MCMCChains.jl/blob/master/src/stats.jl#L340-L354).
`P` is initialized with `P[1] = 1.0` and the following `P[i]` are calculated using `ρ[2i] + ρ[2i + 1]` and stopped when `P[i] < 0` thus the sum is always greater than 1.
The denominator in `ess[i] = (n*m) / (-1 + 2*sum(P_monotone))` can't ever be smaller than 1.
It's not clear from the literature I read if this is correct or if `P[1]` should also be calculated from `ρ[0] + ρ[1]`. In the later case the sum could become < 1.

Maybe someone can check my reasoning on this.

**Comment by cpfiffer** [comment]
That was my first thought as well. From the [Stan's implementation](https://github.com/stan-dev/stan/blob/develop/src/stan/analyze/mcmc/compute_effective_sample_size.hpp), it seems that it should actually be initialized to zero:

```cpp
Eigen::VectorXd rho_hat_s(num_draws);
rho_hat_s.setZero();
```

The second item in the vector is 

```cpp
double rho_hat_even = 1;
double rho_hat_odd = 1 - (mean_var - acov_s.mean()) / var_plus;
rho_hat_s(1) = rho_hat_odd;
```

But I do those transformations earlier in the code.

So we should have `P[1] = 0`. I think that @benelsen nailed it. There might also be something else happening here, but I'll have to muck around a bit more. 

Sorry I dropped the ball on this one. I blame it on the fact that reading C++ makes me break out in hives and curse fate for my great misfortune.

**Comment by goedman** [comment]
Thanks Cameron, I think I ran this [script](https://github.com/TuringLang/MCMCChains.jl/issues/86#issuecomment-487399238) previously and will update this to provide a graph like [this](https://github.com/TuringLang/MCMCChains.jl/issues/86#issuecomment-488269350).

**Comment by goedman** [comment]
Hi Cameron,

Updated (simplified) the script to:
```
using CmdStan, StatsPlots, Random, MCMCDiagnostics

Random.seed!(12395391)

ProjDir = @__DIR__
cd(ProjDir)

berstanmodel = "
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  theta ~ beta(1,1);
  for (n in 1:N) 
    y[n] ~ bernoulli(theta);
}
"

data = Dict("y" => [0,1,0,0,0,0,0,0,0,1],
  "N" => 10)

stanmodel = Stanmodel(
   name = "berstanmodel", model = berstanmodel, nchains = 4);


ess_array_mcmcchains = []
ess_array_cmdstan = []

for i in 1:100
  rc, chns, cnames = stan(stanmodel,
     data, summary=true, ProjDir);
  dfc = describe(chns)[1]
  append!(ess_array_mcmcchains, dfc[:theta, :ess])
  rs = read_summary(stanmodel)
  append!(ess_array_cmdstan, rs[:theta, :ess])
end

p = Array{Plots.Plot{Plots.GRBackend}}(undef, 1);
p[1] = plot(ess_array_cmdstan, lab="CmdStan", xlim=(0, 170))
p[1] = plot!(ess_array_mcmcchains, lab="MCMCChains")
plot(p..., layout=(1,1))
savefig("ess_comparison_plot.pdf")
```

This shows a bias now for the csp/ess_preset branch (below ..._plot_1 is using master, ..._plot is the ess_preset branch).

[ess_comparison_plot_1.pdf](https://github.com/TuringLang/MCMCChains.jl/files/3293450/ess_comparison_plot_1.pdf)
[ess_comparison_plot.pdf](https://github.com/TuringLang/MCMCChains.jl/files/3293451/ess_comparison_plot.pdf)

**Comment by cpfiffer** [comment]
Just so you folks know, I haven't forgotten about this issue. I've been traveling and working on a big Turing update recently that's been occupying me.

**Comment by goedman** [comment]
Thanks Cameron!

**Comment by cpfiffer** [comment]
I've updated the fix and moved it over to #122. Anyone have further thoughts on testing this?

**Comment by goedman** [comment]
I'll try to find a working example that shows negative correlation.

**Comment by cpfiffer** [comment]
That'd be super helpful. I only tried a couple models but I wasn't able to get somthing that demonstrates this behavior.

**Comment by goedman** [comment]
Haven't forgotten this one but it needs some updates to MCMCBenchmarks.jl.
