### ISSUE TITLE
display and println behave different on chains

### ISSUE THREAD

**Issue by xukai92** [TuringLang/MCMCChains.jl#118]
`display` will not show `r_hat` but `println` will

**Comment by cpfiffer** [comment]
This was a design choice. `display` works the Julian way, which is only to display a subset of your data that fits in the screen. `println` is much more forceful in that it shows everything -- this is for people who have small screens or something but want to show everything.

**Comment by cpfiffer** [comment]
I'll close this for now. I'm fine with reopening this if people don't like this choice, I really don't have strong opinions on it.
