### ISSUE TITLE
Issues with DataFrames/

### ISSUE THREAD

**Issue by goedman** [TuringLang/MCMCChains.jl#126]
Hi Cameron,

I noticed recently the following warning:
```
┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
```
It happens when I select from a ChainDataFrame:
```
cdf[:theta, :mean]
```
I think it was introduced by the latest DataFrames update that expect the `df[!, ...]` syntax.

Initial testing with Julia 1.4, as Julia 1.3.0-rc1 gave problems, might show another issue with both DataFrames and MCMCChains exporting `describe`. But I need to further check that.

**Comment by goedman** [comment]
Hi Cameron, I tested with 2 updates in summarize.jl:
lines 71 & 92: `.df[:,`   -> .`df[!,`

Not sure if those are all cases, but it stops the warnings when I test Stan.jl.

**Comment by cpfiffer** [comment]
I'll get a PR in to fix this everywhere, thanks!

**Comment by yebai** [comment]
Is this fixed now?

**Comment by goedman** [comment]
Yes, I believe it is fixed!
