### ISSUE TITLE
Replace Plots.jl dependency by RecipesBase.jl

### ISSUE THREAD

**Issue by theogf** [TuringLang/MCMCChains.jl#151]
Plots.jl is a very heavy dependency and could be replaced by [RecipesBase.jl](https://github.com/JuliaPlots/RecipesBase.jl)

**Comment by theogf** [comment]
Ah just realised this has been fixed already and I had a older version, sorry for the noise...

**Comment by cpfiffer** [comment]
No worries, thanks!
