### ISSUE TITLE
unsorted Parameters are being sorted - but the data isn't

### ISSUE THREAD

**Issue by mdkeehan** [TuringLang/MCMCChains.jl#157]
I have built a little test to show what I believe is an error that I am seeing.
Parameters are being sorted but the resulting data isn't. Thus leading to errors.

```julia
using MCMCChains
using Test
val=rand(13,3,1)

parametersArray=["P3","P2","P1"]

Test.@testset "MCMCChain construction by unsorted array" begin
    chn=Chains(val,parametersArray)

    for( i,p) in enumerate(parametersArray)
        @test String(summarystats(chn)[:parameters][i]) == parametersArray[i]
    end
end
```

**Comment by mdkeehan** [comment]
```
(v1.1) pkg> st MCMCChains
    Status `~/.julia/environments/v1.1/Project.toml`
  [a93c6f00] DataFrames v0.19.4
  [31c24e10] Distributions v0.21.10
  [c7f686f2] MCMCChains v0.4.0
  [9a3f8284] Random 

(v1.1) pkg>
```

**Comment by cpfiffer** [comment]
I don't see how this test is checking whether the values are sorted? Parameters are sorted by default using natural sort order. For example, here's the value stored in the chain, and then the original, unsorted value. As you can see, they have been rearranged accordingly.

```julia
julia> chn.value
3-dimensional AxisArray{Float64,3,...} with axes:
    :iter, 1:1:13
    :var, ["P1", "P2", "P3"]
    :chain, [1]
And data, a 13×3×1 Array{Float64,3}:
[:, :, 1] =
 0.000434168  0.701021  0.666945
 0.559137     0.582236  0.536907
 0.367655     0.628453  0.762061
 0.949062     0.525313  0.46901 
 0.0429379    0.859049  0.724493
 0.279948     0.521807  0.515179
 0.206609     0.909959  0.51648 
 0.665928     0.544363  0.940078
 0.292142     0.480982  0.570149
 0.331067     0.387462  0.268135
 0.247142     0.846159  0.973169
 0.102152     0.507188  0.306246
 0.729446     0.30506   0.325106

julia> val
13×3×1 Array{Float64,3}:
[:, :, 1] =
 0.666945  0.701021  0.000434168
 0.536907  0.582236  0.559137   
 0.762061  0.628453  0.367655   
 0.46901   0.525313  0.949062   
 0.724493  0.859049  0.0429379  
 0.515179  0.521807  0.279948   
 0.51648   0.909959  0.206609   
 0.940078  0.544363  0.665928   
 0.570149  0.480982  0.292142   
 0.268135  0.387462  0.331067   
 0.973169  0.846159  0.247142   
 0.306246  0.507188  0.102152   
 0.325106  0.30506   0.729446 
```

If you don't like the sorting behavior, you can pass `sorted=false` when you construct a chain to maintain the original sorting behavior:

```julia
julia> chn_unsorted = Chains(val, parametersArray, sorted=false);

julia> chn_unsorted.value
3-dimensional AxisArray{Float64,3,...} with axes:
    :iter, 1:1:13
    :var, ["P3", "P2", "P1"]
    :chain, [1]
And data, a 13×3×1 Array{Float64,3}:
[:, :, 1] =
 0.666945  0.701021  0.000434168
 0.536907  0.582236  0.559137   
 0.762061  0.628453  0.367655   
 0.46901   0.525313  0.949062   
 0.724493  0.859049  0.0429379  
 0.515179  0.521807  0.279948   
 0.51648   0.909959  0.206609   
 0.940078  0.544363  0.665928   
 0.570149  0.480982  0.292142   
 0.268135  0.387462  0.331067   
 0.973169  0.846159  0.247142   
 0.306246  0.507188  0.102152   
 0.325106  0.30506   0.729446   
```

**Comment by mdkeehan** [comment]
Hi,
 
Thanks for pointing out the `sorted=false` parameter - that is the behaviour I was expecting by default. I didn't find the significance of the parameter in the documentation.

I have tried to show a code path using the default settings and how it could lead mislead a user. The default path should be the least unexepcted path. Could the default sort action be changed for when the user passes in an array of String?  

```julia
using MCMCChains
using LinearAlgebra

val=rand(13,3,1)
val[:,:,1] *= diagm([ 1000.0,10.0,1.0])
parameterNames=["P1000","P10","P1"]
summarystats(Chains(val,parameterNames))[:mean,]
```

**Comment by cpfiffer** [comment]
Doing so changes the default for all constructors, so the better question is whether the sorting behavior needs to be changed everywhere. There have been several issues about this in the past, which suggests to me that many people find default natural sort order unpleasant. 

I'm fine with changing the default to unsorted. We'd just need to contact people who use MCMCChains in their respective packages to make sure that they set convenient defaults for their particular use cases. 

@goedman does removing the sort by default work for you? You can keep the current behavior by setting `sorted=true` in CmdStan constructors if you prefer the sorting functionality.

**Comment by goedman** [comment]
It's hard to estimate how much work is involved (or not), but if the consensus is to switch the sorting off by default let's go for it.

**Comment by cpfiffer** [comment]
As of MCMCChains 1.0+, chains will no longer be sorted by default, thanks to #160 .
