### ISSUE TITLE
Has v1.0 been merged?

### ISSUE THREAD

**Issue by goedman** [TuringLang/MCMCChains.jl#163]
Hi Cameron,

Just a bit confused if v1 has been released? I noticed that TagBot action is not active.

Thanks,
Rob

**Comment by cpfiffer** [comment]
No, I think I was hoping to have #156 in before then, but I think it's fine to release now.

We don't use TagBot with Actions -- I think you can just click a button somewhere and TagBot just works without you having to set up a GitHub workflow.

@JuliaRegistrator register

**Comment by cpfiffer** [comment]
Cool, v1.0 is out!

**Comment by goedman** [comment]
Thank you!
