### ISSUE TITLE
Utilities for extracting X from chains

### ISSUE THREAD

**Issue by xukai92** [TuringLang/MCMCChains.jl#178]
To make extraction easy-to-use, we probably want to consider implementing utilites for the following features

- Extract internal parameters
    - E.g. `chn.tree_depth`
    - Maybe it's already possible but not documented on the README.
- Extract summary statistics
    - E.g. `chn.ess`

**Comment by devmotion** [comment]
I haven't tried it, but I assumed the internal parameters could be extracted in the same way as regular parameters. There are some examples in the README but maybe that's not clear?

For the diagnostics, there exist functions such as `ess` which are exported. I guess that's what you're interested in?

**Comment by cpfiffer** [comment]
You should be able to do `chain[:tree_depth].value.data` to get an `Array` out. Perhaps we could allow `getproperty` so that 

```julia
getproperty(chain::Chains, sym::Symbol) = chain[sym].value.data
```

Then you can just get the data you want in array form without having to deal with a new chain, which is behavior I am not too fond of anyway.

**Comment by trappmartin** [comment]
This sounds as if it is already supported. Would it make sense to add convenience functions, such as `internals(chn)` and `parameters(ch)` which essentially are a wrapper?

**Comment by xukai92** [comment]
MCMCDiagnosticTools.jl has these utility interfaces (https://beta.turing.ml/MCMCDiagnosticTools.jl/dev/).
