### ISSUE TITLE
Do not mix String and Symbol

### ISSUE THREAD

**Issue by devmotion** [TuringLang/MCMCChains.jl#185]
It seems there are many places where we convert from String to Symbol and vice versa, even though it might not be needed, or allow both (vectors of) String and Symbol as keyword arguments. I think to avoid inconsistencies (such as the one I noticed in https://github.com/TuringLang/MCMCChains.jl/pull/184), we should try to consistently use only one of them (I'm in favour of Symbol), and only convert if it can't be avoided.

**Comment by cpfiffer** [comment]
I was planning on opening a similar issue today. Initially, I wanted to have a permissive system that allowed users to choose between the two, but now it's just annoying. I am also in favor of `Symbol`.

**Comment by devmotion** [comment]
Closed by https://github.com/TuringLang/MCMCChains.jl/pull/197.
