### ISSUE TITLE
hpd is broken

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/MCMCChains.jl#196]
Hi-

I want to report that the function hpd is broken. It is possible that other statistic functions are broken due to breaking changes (see [cor](https://github.com/TuringLang/MCMCChains.jl/issues/189) as another example). Here is a MWE:

```
using MCMCChains
import MCMCChains: hpd
val = rand(500, 5, 2)
chn = Chains(val, ["a", "b", "c", "d", "e"])
hpd(chn)
hpd(chn; digits=3)
```

On slack Miles Lucas provided an untested workaround. I will include it in case it is helpful.

```
function hpd(arr::AbstractVector,  alpha=0.05)
    low = alpha/2
    high = 1 - alpha/2
    k = kde(arr)

    finite_cdf = cumsum(k.density)
    idx1 = findfirst(phi->phi > low, finite_cdf)
    idx2 = findlast(phi->phi < high, finite_cdf)
    return k.x[[idx1, idx2]]
end
```

Version:

```
(@v1.4) pkg> st MCMCChains
Status `~/.julia/environments/v1.4/Project.toml`
  [c7f686f2] MCMCChains v3.0.5
```

Julia 1.4

**Comment by devmotion** [comment]
I added a fix to https://github.com/TuringLang/MCMCChains.jl/pull/194.

**Comment by itsdfish** [comment]
Thanks for making these changes and releasing a new version so quickly.
