### ISSUE TITLE
Unexpected number of samples returned from `sample`

### ISSUE THREAD

**Issue by jerome-white** [TuringLang/MCMCChains.jl#223]
The `sample` parameter `n` determines the number of samples to retrieve. However, it returns more than that for "multi" chains. Consider the following:

```julia
using Turing, MCMCChains

@model gdemo(x, y) = begin
    σ ~ InverseGamma(2,3)
    μ ~ Normal(0,sqrt(σ))

    x ~ Normal(μ, sqrt(σ))
    y ~ Normal(μ, sqrt(σ))
end
s = sample(gdemo(1, 2), HMC(0.01, 5), MCMCThreads(), 2, 4)

x = 4
(rows, _) = size(Array(sample(s, x)))
@assert rows == x
```

I was expecting it to return `n` number of samples per parameter, not `n * JULIA_NUM_THREADS`. Is this behaviour intended?

**Comment by devmotion** [comment]
Actually I don't know if it's intended, it seems already when the sampling functionality was added it was implemented just as sampling a subset of iterations and returning the subset of the chain at these iterations. Hence if one has a `Chains` object with multiple chains, as in your case, one gets a `Chains` object of dimensions `n x num_params x num_chains`, where `n` is the number of samples.

When you convert the `Chains` object to an `Array` these chains are appended, and hence you get `n x num_chains` samples per parameter. You can change that with the keyword argument `append_chains = false`.

Maybe @cpfiffer or @goedman (who wrote the initial implementation if I'm not mistaken) know more about why this particular `sample` algorithm was chosen and implemented.

**Comment by cpfiffer** [comment]
I don't think that should be the intended behavior -- it should just return `n` samples.

**Comment by goedman** [comment]
Docs:
```
# By default chains are appended. This can be disabled
# using the append_chains keyword argument:
Array(chns, append_chains=false)

# This will return an `Array{Array, 1}` object containing
# an Array for each chain.
```

**Comment by jerome-white** [comment]
It looks like the `append_chains=false` keyword argument also exists for the DataFrame constructor and is semantically equivalent (to what it means for Array). For now I can use that to craft a solution.

More generally, however, is there a programmatic way of accessing individual chains? Something like
```julia
chn = Chains(...)
each_chain = split(chn)
```

**Comment by devmotion** [comment]
You could just use indexing:
```julia
each_chain = [chn[:, :, i] for i in 1:size(chn, 3)]
```
