### ISSUE TITLE
Computed log pointwise predictive density

### ISSUE THREAD

**Issue by PToTheK** [TuringLang/MCMCChains.jl#243]
Hi there,
I would like to compute the WAIC information criterion for a fitted Bayesian model.

However, in doing so one has to evaluate the computed log pointwise predictive density, as defined in Eq.(3) in:
https://arxiv.org/pdf/1507.04544.pdf

Specifically I don't know how to compute the term:
```LaTeX
p(y_i, \theta^s),
```
which should be the likelihood with the sampled parameter values from the posterior.

How do I compute that with the returned chains from a NUTS() sampling?

Thanks for your help!!!

**Comment by devmotion** [comment]
Hi!

So it seems you want to compute the elementwise log-likelihoods? In that case probably you should use [`elementwise_loglikelihoods`](https://github.com/TuringLang/DynamicPPL.jl/blob/37ec450a5c8016d1985cd9c38504808418748152/src/loglikelihoods.jl#L94-L163) which @torfjelde just added to DynamicPPL. He also added [an example](https://arviz-devs.github.io/ArviZ.jl/dev/quickstart/#Additional-information-in-Turing.jl) to the ArviZ docs that shows how this function can be used to compute LOO.

**Comment by PToTheK** [comment]
Thank you very much @devmotion for this fast response and for the links!
I will check these out and leave a reply once I see if this works.

**Comment by torfjelde** [comment]
Following the above example you can also just use `ArviZ.waic` directly instead of implementing your own, if you'd like :+1: 

Also, @devmotion I believe I misremembered when I said I thought "elementwise likelihood` was being used in the literature; I was thinking of "pointwise likelihood" :confused:

**Comment by devmotion** [comment]
> Also, @devmotion I believe I misremembered when I said I thought "elementwise likelihood` was being used in the literature; I was thinking of "pointwise likelihood" confused

We can just rename it to `pointwise_loglikelihoods` and deprecate `elementwise_loglikelihoods` :slightly_smiling_face:

**Comment by torfjelde** [comment]
> We can just rename it to pointwise_loglikelihoods and deprecate elementwise_loglikelihoods 

Honestly, that sounds like a good idea to me :+1:

**Comment by torfjelde** [comment]
This can be closed, right?

**Comment by PToTheK** [comment]
Yes, thanks again!
