### ISSUE TITLE
Implementation of Tables interface is incorrect

### ISSUE THREAD

**Issue by devmotion** [TuringLang/MCMCChains.jl#268]
The implementation of the Tables interface is not correct. According to the [documentation](https://tables.juliadata.org/dev/#Implementing-the-Interface-(i.e.-becoming-a-Tables.jl-source)-1), `Tables.rows` has to return an `Tables.AbstractRow`-compatible **iterator**. However, currently it just returns the `Chains` object itself. From the documentation it is unclear to me if the `Tables.AbstractColumns`-compatible object that should be returned by `Tables.columns` should implement the iteration interface as well (it is provided for subtypes of `Tables.AbstractColumns` automatically). 

For instance, Pluto relies on the convention that `Tables.rows` returns an iterator in the implementation of its display mechanism in https://github.com/fonsp/Pluto.jl/blob/6800da3b40a5e38aed465067b38751f6e6479649/src/runner/PlutoRunner.jl#L838. Therefore, currently an error is thrown if one tries to display a `Chains` object in Pluto (e.g., if it is returned from a function call).

**Comment by sethaxen** [comment]
IIRC I patterned the Tables interface implementation after DataFrames.jl's implementation. I'll look into this.
