### ISSUE TITLE
Documentation not built for stable

### ISSUE THREAD

**Issue by rikhuijzer** [TuringLang/MCMCChains.jl#277]
For some reason, the documentation isn't tagged for stable, so the stable button in the README is broken. I'm eyeballing https://discourse.julialang.org/t/documenter-jl-does-not-build-on-tags-anymore-after-renaming-master-to-main/57171/4 in the hope that it is caused by the same thing, but probably not.

**Comment by devmotion** [comment]
The documentation should be built also when there's a new tag (i.e., a new stable release). It seems that's not done currently. Probably best to move it to a separate action to avoid having to rerun the tests if a new version is tagged.

**Comment by devmotion** [comment]
Should be fixed by https://github.com/TuringLang/MCMCChains.jl/pull/278.

**Comment by rikhuijzer** [comment]
Thanks for looking into it!
