### ISSUE TITLE
MCMCChain name should ideally be plural

### ISSUE THREAD

**Issue by mkborregaard** [TuringLang/MCMCChains.jl#29]
The Julia naming guidelines normally is to have the type name be plural: `MCMCChains`. Maybe it's too late now, but this trips me every time.

**Comment by cpfiffer** [comment]
I'd agree with this. Every time I try go to this repo I end up typing `MCMCChains` in the address bar and go somewhere other than where I'd like to be. I would agree that it's maybe too late, though.

**Comment by mkborregaard** [comment]
FWIW we're planning to change the name StatPlots to StatsPlots for consistency with StatsKit, StatsModels, StatsBase etc.

**Comment by yebai** [comment]
> FWIW we're planning to change the name StatPlots to StatsPlots for consistency with StatsKit, StatsModels, StatsBase etc.

Happy to change the package name to `MCMCChains`! However, is there a good way of doing that without registering a new package?

**Comment by mkborregaard** [comment]
I believe the official steps are here: https://discourse.julialang.org/t/changing-the-name-of-a-package/14960/5
That's the careful way. For PlotRecipes, which we recently renamed to GraphRecipes, we simply changed the name of the github repo and announced it on discourse, because we assessed only few people were using it anyway.

**Comment by goedman** [comment]
Double true for StanMCMCChain, in fact when I did that package I raised this issue as well. Happy to change the name and references. StatisticalRethinking is just a simple edit.

**Comment by mkborregaard** [comment]
StatisticalRethinking wouldn't need to change, right? I believe this is only necessary when the package is named after the types it provides. Sorry if I'm misunderstanding here.

**Comment by goedman** [comment]
Just an update of ‘using MCMCChain’.

**Comment by mkborregaard** [comment]
I've asked on Slack about the repo change

**Comment by trappmartin** [comment]
I’m happy to change the name too. In fact we discussed this a few times and I’m happy if we eventually do it. I’m currently in Greece but back on my PC in about a week and could do the required steps.

**Comment by trappmartin** [comment]
@goedman I think we should change the name of the package after the following issues: #30, #24, #28 are fixed which should be soon.

**Comment by goedman** [comment]
That's fine @trappmartin. I also need to wait for @mkborregaard's  renaming of StatPlots to StatsPlots has settled (I see the depreciation warnings but can't `] add StatsPlots` yet). By the way, do you understand the https://github.com/TuringLang/Turing.jl/issues/635#issue-394816862 issue?

**Comment by cpfiffer** [comment]
I'm currently working on a way to address that issue, along with general usability and robustness for the `Chains` object.
