### ISSUE TITLE
problem with MCMCChains.Chains() on Julia 1.7beta2

### ISSUE THREAD

**Issue by mcreel** [TuringLang/MCMCChains.jl#312]
chn=Chains(rand(10,2), ["a", "b"]) works fine on Julia 1.6.1, but errors on 1.7beta2

❯ ~/julia-1.7.0-beta2/bin/julia --project
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0-beta2 (2021-06-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using MCMCChains

julia> chn = Chains(rand(10,2), ["α", "β"])
┌ Warning: use values(kwargs) and keys(kwargs) instead of kwargs.data and kwargs.itr
│   caller = #AxisArray#7 at core.jl:243 [inlined]
└ @ Core ~/.julia/packages/AxisArrays/IFpjG/src/core.jl:243
ERROR: type DataType has no field names
Stacktrace:
  [1] getproperty(x::Type, f::Symbol)
    @ Base ./Base.jl:37
  [2] #s11#8
    @ ~/.julia/packages/AxisAr

**Comment by devmotion** [comment]
This problem seems to be caused by AxisArrays: https://github.com/JuliaArrays/AxisArrays.jl/issues/200
