### ISSUE TITLE
Remove MCMCChain from general registry?

### ISSUE THREAD

**Issue by rikhuijzer** [TuringLang/MCMCChains.jl#321]
I noticed that Nanosoldier is reporting test failures on [Julia 1.7](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/e04e3e1_vs_96386f9/report.md) for the package `MCMCChain` (note the missing `s`).

This package is in the registry linked to <https://github.com/TuringLang/MCMCChain.jl/> which redirects to <https://github.com/TuringLang/MCMCChain.jl/> , but it is not updated by `JuliaRegistrator`. Therefore, it is currently at version `0.2.3` (MCMCChains is at `4.13.1`), which can be seen [here](https://github.com/JuliaRegistries/General/blob/master/M/MCMCChain/Versions.toml) or by running `add MCMCChain` locally.

Should an attempt be made to remove `MCMCChain` from the registry to avoid confusion?

**Comment by yebai** [comment]
Happy to remove it - is that practically possible?

**Comment by rikhuijzer** [comment]
I've opened an issue at https://github.com/JuliaRegistries/General/issues/41567.
