### ISSUE TITLE
"Wrong" order from names(chain, :parameters)

### ISSUE THREAD

**Issue by knuesel** [TuringLang/MCMCChains.jl#326]
Consider this example:

```julia
@model function mymodel(x)
    σ ~ LogNormal()
    a ~ Normal()
    c ~ Normal()
    b ~ Normal()
    x .~ Normal(a+b+c, σ)
end

model = mymodel(randn(1000))
ch = sample(model, NUTS(0.65), 100)
plot(ch)
```

This plots the parameters in the order `σ`, `a`, `c`, `b`. This matches the order of parameters in the underlying AxisArray. However, retrieving the parameter list with `names` gives a different order:

```julia
julia> names(ch, :parameters)
4-element Vector{Symbol}:
 :a
 :b
 :σ
 :c
```

My use case: I want to add things on the plots created by `plot(ch)`. To modify the plot for the ith parameter I can do `plot!(..., subplot=2i)`. But I can't find a good way to get the list of parameters in the right order...

**Comment by cpfiffer** [comment]
Part of this is because `names` is intended to be used to get out parameters that fall in different sections, so it adds things in a weird order:

https://github.com/TuringLang/MCMCChains.jl/blob/b1e4c0e03f06db975b706724f8bb8dbbf9fdebb2/src/chains.jl#L520-L526

Could this work for you?

```julia
chain.value.axes[2].val
```

**Comment by knuesel** [comment]
But I'm getting the names from one specific section (`:parameters`) :

https://github.com/TuringLang/MCMCChains.jl/blob/b1e4c0e03f06db975b706724f8bb8dbbf9fdebb2/src/chains.jl#L513

so it's not clear why the order would be wrong?

Thanks for the suggestion! I think it's equivalent to `names(chain)` ? It returns the right order, but with lots of other values. So the following workaround seems to work:

```julia
params = names(ch)[1:length(names(ch, :parameters))]
```

**Comment by devmotion** [comment]
The MWE is fixed by https://github.com/TuringLang/MCMCChains.jl/pull/332. With the PR one gets
```julia
julia> names(ch, :parameters)
4-element Vector{Symbol}:
 :σ
 :a
 :c
 :b
```
