### ISSUE TITLE
Dealing with `name_map`

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/MCMCChains.jl#335]
From what I can tell, `name_map` is intended to keep track of parameters of the form `x[1], x[2]`, so they can be treated as one parameter `x`. While working with the MCMCChains codebase over the weekend, I found it kind of annoying to deal with. It feels like de facto mutable state -- even though `Chains` are immutable and so is `name_map`, there are enough functions that return a slightly-different version of a chain that it's practically mutable, and every time I modify the function I have to keep track of `name_map` and make sure it's up-to-date in all the functions I work with.

My proposal is we remove `name_map`, then overload indexing so that indexing into `chains["var"]` first searches through the array for `"var"` and then, if an exact match for `"var"` is not found, searches for any variable that looks like `"var[i]"`. I think this would be more intuitive and easier to maintain.

**Comment by devmotion** [comment]
> My proposal is we remove name_map, then overload indexing so that indexing into chains["var"] first searches through the array for "var" and then, if an exact match for "var" is not found, searches for any variable that looks like "var[i]". I think this would be more intuitive and easier to maintain.

I.e., it could return `chain[:var]` (BTW everything is based on symbols) or `chain[[:var[1], :var[2], ...]]`? This seems a lot like the old design which caused type instabilities and luckily we could get rid of. I'll see if I can find the PR to make sure I remember it correctly.

**Comment by devmotion** [comment]
This is the PR I had in mind: https://github.com/TuringLang/MCMCChains.jl/pull/197 Seems some prior discussion is in other issues or PRs though.

**Comment by ParadaCarleton** [comment]
> > My proposal is we remove name_map, then overload indexing so that indexing into chains["var"] first searches through the array for "var" and then, if an exact match for "var" is not found, searches for any variable that looks like "var[i]". I think this would be more intuitive and easier to maintain.
> 
> I.e., it could return `chain[:var]` (BTW everything is based on symbols) or `chain[[:var[1], :var[2], ...]]`? This seems a lot like the old design which caused type instabilities and luckily we could get rid of. I'll see if I can find the PR to make sure I remember it correctly.

Hmm, interesting; I hadn't considered possible type instabilities. In that case, maybe we should replace `name_map` with a function that computes the appropriate names, and give that function a shorter name? e.g. `vars(:x)` returns `chain[:x[1], :x[2]...]`. So we can avoid having to keep track of the `name_map` field.

**Comment by ParadaCarleton** [comment]
Actually, am I maybe misunderstanding what `name_map` does? I was under the impression that sections+groups were the same thing, but I'm not sure about that anymore now that I've taken a closer look through the code.

**Comment by devmotion** [comment]
> How does name_map fix this type instability?

It doesn't, my comment was related to your suggestion of first looking for `:var` and if not existent for `:var[` etc.

> I was under the impression that sections+the groups referred to in namesingroup were the same thing, but I'm not sure about that now that I've taken a closer look through the code. I'm not sure I see what the sections in name_map are used for, if it's not that.

No, `name_map` is not used for the **groups** returned by `namesingroup` (BTW `namesingroup` is explained e.g. [here](https://turinglang.github.io/MCMCChains.jl/dev/chains/#MCMCChains.namesingroup-Tuple{Chains,%20String})). `name_map` declares which variables in the array belong to which **section**. Most importantly, it stores which variables belong to the `parameters`, i.e., which ones are actual MCMC samples, and which ones are just internal metadata such as `lp` (log probability) values in the example in the AdvancedMH README:
```julia
Object of type Chains, with data of type 100000×3×1 Array{Float64,3}

Iterations        = 1:100000
Thinning interval = 1
Chains            = 1
Samples per chain = 100000
internals         = lp
parameters        = μ, σ

2-element Array{ChainDataFrame,1}

Summary Statistics

│ Row │ parameters │ mean     │ std      │ naive_se    │ mcse       │ ess     │ r_hat   │
│     │ Symbol     │ Float64  │ Float64  │ Float64     │ Float64    │ Any     │ Any     │
├─────┼────────────┼──────────┼──────────┼─────────────┼────────────┼─────────┼─────────┤
│ 1   │ μ          │ 0.156152 │ 0.19963  │ 0.000631285 │ 0.00323033 │ 3911.73 │ 1.00009 │
│ 2   │ σ          │ 1.07493  │ 0.150111 │ 0.000474693 │ 0.00240317 │ 3707.73 │ 1.00027 │

Quantiles

│ Row │ parameters │ 2.5%     │ 25.0%     │ 50.0%    │ 75.0%    │ 97.5%    │
│     │ Symbol     │ Float64  │ Float64   │ Float64  │ Float64  │ Float64  │
├─────┼────────────┼──────────┼───────────┼──────────┼──────────┼──────────┤
│ 1   │ μ          │ -0.23361 │ 0.0297006 │ 0.159139 │ 0.283493 │ 0.558694 │
│ 2   │ σ          │ 0.828288 │ 0.972682  │ 1.05804  │ 1.16155  │ 1.41349  │
```
