### ISSUE TITLE
Warning: timestamp

### ISSUE THREAD

**Issue by enweg** [TuringLang/MCMCChains.jl#360]
https://github.com/TuringLang/MCMCChains.jl/blob/e898e9f431572248047f34a20e3f34b5f0feb805/docs/src/getting-started.md?plain=1#L25

I was just trying out MCMCChains and noticed that every time I create a new chain, I get a warning saying 

Warning: timestamp of type Nothing unknown

This seems to be caused by https://github.com/TuringLang/MCMCChains.jl/blob/042236a59f09e46d2e032e9cc16d684a900d1842/src/chains.jl#L363

I do see the usefulness of having timestamps, and I love that Turing will give me an approximate sampling time, but is it somehow possible to turn this off?

**Comment by ParadaCarleton** [comment]
I don't think this should throw a warning; it's definitely annoying and clutters up the REPL for me, and it seems like it's quite likely going to cause alarm fatigue. @cpfiffer should I make a PR removing this?

**Comment by cpfiffer** [comment]
Yeah, let's remove it. I'm not a fan.

**Comment by devmotion** [comment]
Fixed by https://github.com/TuringLang/MCMCChains.jl/pull/372.
