### ISSUE TITLE
margin control in corner plot

### ISSUE THREAD

**Issue by fkrauer** [TuringLang/MCMCChains.jl#369]
Hi everyone

Is it possible to control the plot margin width between the individual parameter panels in the corner plot? I have quite a few params, and the resulting corner plot is very hard to read and wastes some space:
![cornerplot](https://user-images.githubusercontent.com/36159611/167474016-3210d32c-90b1-45fc-a43e-2a77bfd55e00.png)
I was also wondering if it would be an interesting option to add the correlation coefficients in the upper triangle, as in this example (this plot is done with `correlationPlot()` from the R package `BayesianTools`. I can add it myself, but thought it might be interesting for others too. 
![corrplot](https://user-images.githubusercontent.com/36159611/167474310-5ce2de20-587d-47df-9d9a-8876a96843ef.png)

**Comment by devmotion** [comment]
You should be able to use all (Stats)Plots customizations that apply to `cornerplot` (see e.g. https://github.com/JuliaPlots/StatsPlots.jl#corrplot-and-cornerplot and https://github.com/JuliaPlots/StatsPlots.jl/blob/master/src/cornerplot.jl). There's e.g. a `margin` option but I don't know what exactly it controls.

**Comment by mkborregaard** [comment]
Yes, setting `margin` to a negative value should do the trick here. The default margins don't take the subplot size into account. The idea of the correlation coeffecients could be opened as an issue on StatsPlots
