### ISSUE TITLE
MCMCChains.jl exports "plot"

### ISSUE THREAD

**Issue by dcarrera** [TuringLang/MCMCChains.jl#37]
The MCMCChain.jl package adds a "plot" function to the global namespace based on Plots.jl. This creates a problem for those of us who do not use Plots.jl as our preferred plotting package. I think that an MCMC code should not be polluting the global namespace with plotting functions and causing issues with people who do not share the developers' preference of plotting package. An MCMC code is not a plotting module. It should be possible (and default) to get the MCMC features alone.

Would it be possible for MCMCChain.jl to explicitly only overwrite `Plots.plot` or maybe check whether `Plots` is even being used?

**Comment by cpfiffer** [comment]
I've opened #39 to address this, which does not load any plotting functionality unless a user calls `using StatsPlots` or `using Plots`. 

Please be aware that this package is currently undergoing a name change (from `MCMCChain` to `MCMCChains`) and some fairly significant refactoring on the back end. After #39 is through, the fix will show up in a new package `MCMCChains`, not `MCMCChain`. You can see the progress of the package registration issue [here](https://github.com/JuliaLang/METADATA.jl/pull/21638).

**Comment by mkborregaard** [comment]
I agree that the package should never pollute the global namespace with plotting functions, but this is easy to fix. See my comment on the PR.

**Comment by cpfiffer** [comment]
Closed by #39.
