### ISSUE TITLE
Is MCMCChain still around?

### ISSUE THREAD

**Issue by goedman** [TuringLang/MCMCChains.jl#38]
Did we move (as in a github repo move) or copy (the contents of) MCMCChain to MCMCChains?

**Comment by cpfiffer** [comment]
The repository was only renamed, and @yebai opened up a new registration issue, in order to maintain past issues and pull requests.

**Comment by goedman** [comment]
Ok. In that case we (I) need to be more careful. Do we want master to work with the current Turing?

**Comment by cpfiffer** [comment]
No, I have a separate pull request over there to handle all that. We should be good for the moment assuming nobody is hanging out on the master branch.
