### ISSUE TITLE
Serialization tests failing after type redefinition

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/MCMCChains.jl#40]
I just changed the type definition of `Chains.value` from 

```julia
value::AxisArray
```

to

```julia
value::AxisArray{Union{Missing,A},3}
```

The stored chain binary at `test/sections_m10.4s.jls` is now no longer of the same size -- @goedman would you mind if I wrote a slightly more robust test using random numbers?

**Comment by goedman** [comment]
That would be great, this was intended as a placeholder until we can create an MCMCChains.Chains object from Turing and pushing the current sections implementation by creating a (useful) third section.

**Comment by cpfiffer** [comment]
Ah, okay. That sounds like a plan. I'll leave this open until the Turing integration goes through, and then I'll revisit the testing suite a little more.
