### ISSUE TITLE
Chain summary as default show method.

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/MCMCChains.jl#43]
We currently do not have a convenient `show` method. It would be good if we run `summary stats` the first time `show` is called, cache the computation and display the summary + further infos on the chains object each time the user calls `show`.

**Comment by cpfiffer** [comment]
Cloed by #44.

**Comment by goedman** [comment]
This looks good Cameron! A lot of improvements! Over the last couple of years I have had a few requests for a small summary table that can be read back in for model comparisons. Show and chain summaries are both text based. I'll have a look.

It also seems MCMCChains 0.3.0 works and solves the 0.2.4 problem I reported earlier! Huge progress!
