### ISSUE TITLE
Formatting.jl is being deprecated

### ISSUE THREAD

**Issue by mattiasvillani** [TuringLang/MCMCChains.jl#453]
I get the message below in Julia 1.10.1. MCMCChains.jl is the responsible package since:

 pkg> why Formatting
  MCMCChains → Formatting

Formatting
│  ┌ Warning: DEPRECATION NOTICE
│  │ 
│  │ Formatting.jl has been unmaintained for a while, with some serious
│  │ correctness bugs compromising the original purpose of the package. As a result,
│  │ it has been deprecated - consider using an alternative, such as
│  │ `Format.jl` (https://github.com/JuliaString/Format.jl) or the `Printf` stdlib directly.
│  │ 
│  │ If you are not using Formatting.jl as a direct dependency, please consider
│  │ opening an issue on any packages you are using that do use it as a dependency.
│  │ From Julia 1.9 onwards, you can query `]why Formatting` to figure out which
│  │ package originally brings it in as a dependency.
│  └ @ Formatting ~/.julia/packages/Formatting/3VxOt/src/Formatting.jl:12

**Comment by devmotion** [comment]
I assume you're not using the latest version of MCMCChains (6.0.6) since that one does not depend on Formatting anymore (https://github.com/TuringLang/MCMCChains.jl/pull/451). Can you check whether updating MCMCChains fixes the issue?

**Comment by mattiasvillani** [comment]
Yes, you are correct, another package was holding me back at MCMCChains v5.7.1. When installing 6.0.6 in a fresh environment, I do not get the Deprecation notice. Thanks for the rapid response!
