### ISSUE TITLE
Is MCMCChains primarily intended for display functionality?

### ISSUE THREAD

**Issue by goedman** [TuringLang/MCMCChains.jl#46]
Hi Cameron,

Just a quick (?) question what the long term vision is for MCMCChains.

As I pointed out elsewhere (I think it was in a PR), I noticed that many MCMCChains functions are display/show oriented, e.g. MCMCChains.hpd(). If I want to plot these bounds, e.g [m2.1t.jl](https://statisticalrethinkingjulia.github.io/TuringModels.jl/latest/02/m2.1t/), I need to extract the Vector of theta values and use quantiles(). Earlier I made a similar observation for ChainSummary results.

Similarly, to clean up the NUTS chains (removing the adaptation draws), I use:
```
# Show corrected results (drop adaptation samples)
names = ["theta"]
a3d = chn[:theta]
chn2 = MCMCChains.Chains(a3d[1001:2000,:,:], 
  names,
  Dict(
    :parameters => names
  )
)
```
which is a bit of extra work. Although this example at some point won't be necessary anymore, there are many other cases where further processing of the draws is needed.

I've also attempted to work directly with the AxisArrays, e.g.:
```
aa3d = chn.value[Axis{:var}([:theta]), Axis{:iter}(draws), Axis{:chain}(1)];
```
but (as I prefer not to expose this to end users) it would require encapsulating these in functions.

Thus my question is if indeed MCMCChains is primarily intended for 'display purposes' or if over time the intention is to add (or facilitate) post processing features? (I don't think there is a right or wrong answer here, at most maybe personal preferences).

**Comment by cpfiffer** [comment]
I'd agree that right now it's pretty unwieldy to hand this stuff around to various computations. I believe the example above 

```julia
# Show corrected results (drop adaptation samples)
names = ["theta"]
a3d = chn[:theta]
chn2 = MCMCChains.Chains(a3d[1001:2000,:,:], 
  names,
  Dict(
    :parameters => names
  )
)
```

can be done as

```julia
chn2 = chn[1001:2000, "theta", :] 
```
Can you see if the above runs on your model? There was a bug on the MCMCChains master branch where this didn't work, and I just pushed a fix. This will break down if you're using a Turing-like model where a vector parameter `a` is broken apart into `a[1]`, `a[2]`, and `a[3]`. We pretty much only use the symbol indexing `chain[:a]` if we want to retrieve the unified vector of `a`. 

But yes, I'd like to make sure that there's approximately zero overhead between having a chain and doing some extra numerical work on it. If you post issues with hang-ups you're having like the above I can find ways to make them quick and easy to use.

**Comment by goedman** [comment]
Yip, that works. What I was really looking for (and now also works) was:
```
chn2 = Chains(chn[draws,:,:], :parameters)
```

Haven't decided yet if a subsequent extension like:
```
chn3 = Chains(chn2, [:par1, :par2])
```
would be useful/needed.

In multilevel models, like m10.4[s,t,d].jl, I will create (as I rework StatisticalRethinkingJulia based on the new MCMCChains section option) a third section, e.g. :pooled, to store the draws for all of the a's. I have tested that in [StanMCMCChains](https://github.com/StanJulia/StanMCMCChains.jl/blob/master/examples/m10.4s/m10.4s.jl). Hence I tried to make more than 2 sections part of the section tests. Currently it takes too long to run interesting multilevel models like m10.4t.jl or m12.6t.jl on Travis but I could create a .jls file and restore the Chains object for such a test.

By the way, do you know the reasons for having the chains itself be a Union{Missing, Float64}? Does that happen in Turing? I did see it was a fairly recent addition.

**Comment by goedman** [comment]
Should
```
d, p, c = size(chn2)
```
return d=1000 (when draws=1001:2000)?

**Comment by cpfiffer** [comment]
As to this:

```julia
chn3 = Chains(chn2, [:par1, :par2])
```

It should be fairly trivial to include that, but I think the indexing functionality already covers that. Try `chn3 = chn2[[:par1, :par2]]`.

> By the way, do you know the reasons for having the chains itself be a `Union{Missing, Float64}`? Does that happen in Turing? I did see it was a fairly recent addition.

Yes, my understanding is that the `Union{Missing, Float64}` type was included to pave the way for a couple things we're doing, primarily BNP for random partitions. It's part of [this PR](https://github.com/TuringLang/Turing.jl/pull/591). I think it may be the only thing, but there may be cause in the future to support `Missing` values.

For this:

```julia
d, p, c = size(chn2)
```

I don't know, I suspect that's a matter of taste we should decide on. Currently, the `size` function returns the last value of the range (2000, in your example) and the actual dimensions of `chn.value` for the parameters and chains. It's kind of idiosyncratic and I wasn't sure what to do with it, so I left it in. We can change it if you like, I have no strong feelings on it either way.

**Comment by goedman** [comment]
The example
```
chn3 = chn2[[:par1, :par2]]
```
works fine! I'll do a few more attempts to reformat (or split a parameter section into 2 sections for Turing results).


On the
```
d, p, c = size(chn2)
```
example I believe
```
d, p, c = size(chn.value)
```
returns `d == 1000`.
