### ISSUE TITLE
Unify indexing convention [RFC]

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/MCMCChains.jl#53]
Currently, indexing a `Chains` object can return different object types depending on how you index. 

```julia
# Returns a Chains object with P[1] as its only parameter
chn[:, "P[1]", :] 

# Returns an array of the relevant parameter(s)
chn[:P]
```

I'm not sure I like this. In Turing, `chn[:P]` was honestly much better. If I had a vector of parameters, `chn[:P]` would return a vector of vectors `[ P[1], P[2], P[3] ] `.  In MCMCChains v0.3, you get a flat array where it can be difficult to assign columns to each individual `[ P[1], P[2], P[3] ] `. This behavior is kind of weird though and I think it's better served as a separate, explicit function.

I would like to change indexing so that these two indexing patterns are more consistent. The most obvious choice is that `chn[:P]` should do the same thing as `chn[:,["P[1]", "P[2]", "P3]"],:]` which would return a new `Chains` object containing only `"P[1]", "P[2]", "P[3]"`. 

Would people be okay with that? I would also like to provide an additional function like `get_params` or something, where `get_params(chn, :P)` which would return a tuple looking like `(P[1], P[2], P[3])`. This way, the parameter vectors can be packaged in a more accessible way to users who want to work that way (which I do).

**Comment by goedman** [comment]
Definitely a bit more work for CmdStan & DynamicHMC (not sure about Mamba yet), but I've never liked the current solution in CmdStan when effectively an array is returned.

As you probably have noticed, one of the areas I sometimes get lost in MCMCChains is when to create a new Chains object myself or have MCMCChains handle it for me, e.g. ```chn[:P]```.

I think having users just deal with ```chn[:P]``` and ```chn[draws, :, :]``` would have my preference.

**Comment by cpfiffer** [comment]
What do you mean deal with them? We should or should not unify the behavior between `chn[:P]` and `chn[:,"P[1]",:]`?

**Comment by goedman** [comment]
I would vote to unify them.

I meant folks (hopefully everybody!) wanting to use MCMCChains.Chains not generated by Turing initially will have to create such a chain but after that it would be great if they just can select parameters as you suggest, chns[:P] (and not go the route I often chose to create a new Chains object themselves).

By the way, in your example, P[1], P[2] are just column/parameter names? I mean P is not really a matrix, is it?

**Comment by cpfiffer** [comment]
Yeah, they are columns. P wasn't a matrix. 

So here's what I've come up with. `chn[:P]` and `chn[:,["P[1]", "P[2]", "P3]"],:]` would be equivalent, and I've written a new function that I'm currently calling `get_params`. Here's how it works:

```julia
val = rand(5, 5, 1)

# Make a chain with variables P (1-3), D, and E
chn = Chains(val, ["P[1]", "P[2]", "P[3]", "D", "E"]);

# Get P and D from the chain.
x = get_params(chn, [:P, :D])
```

`get_params` returns a `NamedTuple` with indexes according to the symbols you sent in. Here's the output of `x`, slightly modified for legibility:

```julia
(P = (Union{Missing, Float64}[0.154354; 0.393859; … ; 0.590175; 0.803188], Union{Missing, Float64}[0.837899; 0.97355; … ; 0.0949719; 0.480904], Union{Missing, Float64}[0.681978; 0.931552; … ; 0.949145; 0.741401]), 
 D = Union{Missing, Float64}[0.447698; 0.665995; … ; 0.87924; 0.234808])
```

This is really handy, because now you can do two great things:

```julia
# Get the D vector, which is just a single vector
x.D
```
```
5×1 AxisArray{Union{Missing, Float64},2,Array{Union{Missing, Float64},2},Tuple{Axis{:iter,StepRange{Int64,Int64}},Axis{:chain,Array{Symbol,1}}}}:
 0.4476980787186158 
 0.6659948520690364 
 0.4014649470175069 
 0.8792401370772929 
 0.23480814713911524
```

and you can do

```julia
# Get the P tuple, containing the relevant vectors
x.P
```
```
(Union{Missing, Float64}[0.154354; 0.393859; … ; 0.590175; 0.803188], Union{Missing, Float64}[0.837899; 0.97355; … ; 0.0949719; 0.480904], Union{Missing, Float64}[0.681978; 0.931552; … ; 0.949145; 0.741401])
```

This one in particular is really excellent, because you can do stuff like `x.P[1]`, which gives you the equivalent of `chn.value[:,"P[1]",:]` but allows you to do algorithmic indexing a lot easier.

Thoughts on that behavior?

**Comment by goedman** [comment]
Is this in csp/index-changes? It definitely looks very appealing! I think I see the indexing, get_params is not defined.

**Comment by cpfiffer** [comment]
I changed it from `get_params` to `get`, since I suspect it'll be pretty handy and `get_params` was a bit long. #57 has all the changes in it.

**Comment by cpfiffer** [comment]
Closing in favor of #57.
