### ISSUE TITLE
Expand Utility Functions

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/MCMCChains.jl#65]
It would be helpful to include an easier way to get parameter estimates out of chains.

`mean(chn, :param1)` for example should return the average value. Currently you'd have to do something like `mean(chn[:param1].value.data, dims=1)` which is pretty foolish.

I would also like this to handle cases of vector or matrix valued parameters, which should return a vector of means.

**Comment by goedman** [comment]
Cameron, maybe we should take a broader view of this, e.g. in SR I am playing around with:
```
function chain_to_array(chn::MCMCChains.AbstractChains)
  local a
  for (i, par) in enumerate(names(chn))
    x = get(chn, Symbol(par))
    d, c = size(x[Symbol(par)])
    if i == 1
      a = reshape(convert(Array{Float64}, x[Symbol(par)]), d*c)[:, 1]
    else
      a = hcat(a, reshape(convert(Array{Float64}, x[Symbol(par)]), d*c)[:, 1])
    end
  end
  a
end  
```
and if folks want to continue using data frames ```to_df()```. Something like this function returns an array that can be passed into many, many other functions (kde, plot, ...). Above function simply gets rid of the AxisArrays nature, the Missing union (which we could make an option?) and appends the chains (could also be optional). Selecting which part to convert uses the 'standard' version of ```chns[[:alpha, :sigma]]```

**Comment by cpfiffer** [comment]
I was thinking about this because the `Union{Missing, A}` constraint gets super annoying when I'm trying to take column means and stuff. I removed it a little while but Turing enforces it by default. I think it'd be a good idea to have the above or something like it. I wonder if we might be able to just define an `Array(c::Chains)` constructor as well.

**Comment by goedman** [comment]
That is a great idea! If folks want that they could define DataFrame(c:Chains), NamedArray(c:Chains), etc.

Since you hinted to me about ```names(chn)``` a lot is falling into place. That vector does provide the mapping to the columns in the chn.value AxisArray, which was my big stumble block.

If we would have NamedTupleArray(c:Chains), do we still need get_params?

**Comment by goedman** [comment]
And of course if we have Array(c::Chains) you could internally use it for mean() & friends.

**Comment by cpfiffer** [comment]
> If we would have NamedTupleArray(c:Chains), do we still need get_params?

I'm not sure, what's a `NamedTupleArray`? An array of `NamedTuples`?

> And of course if we have Array(c::Chains) you could internally use it for mean() & friends.

Yeah. I'm not sure though what should be returned if you do something like `mean(chn)` when `chn` has two or more parameters. A dictionary? NamedTuple? Just an array? But then it's tough to map from parameter names to the mean value.

**Comment by goedman** [comment]
Yes, I should have called it an Array{NamedTuple, 1} and it would be something like:
```
[
(alpha=2.401, beta=[0.41, 0.23, 1.14), sigma=3.42),
(alpha=2.392, beta=[0.39, 0.21, 1.16), sigma=3.50),
(alpha=2.398, beta=[0.38, 0.22, 1.21), sigma=3.52),
...
]
```

For ```mean(chn)``` we would get a single NamedTuple? 

I think it is important that names(chn) returns the same vector of names as ```keys(namednuple object)```. A NamedTuple preserves that mapping sequence (this is what through me off for quite a while with chn.value).

**Comment by cpfiffer** [comment]
Oh, gotcha. Yeah, I think the `Array{NamedTuple, 1}` functionality is a good one. My problem with `get` is that it returns a column-oriented data type. I have wanted some kind of row-indexed value like the above that I think'd be nice. 

For `names(chn)` and `keys(get_params(chn, flatten=true))`, we could change the default behavior to `flatten=true`, which would show all the parameter names. The only issue I can see is that the keys of a `NamedTuple` are required to be `Symbols`, but I suppose that's kind of a non-issue if you're indexing. I'll fix the order of these so that they all match.

**Comment by goedman** [comment]
This ```Array{NamedTuple, 1}``` format is used by Tamas Papp in DynamicHMC & Co and works well I think. I also agree that a column oriented format is less useful.

Currently Stings are used in MCMCChains during the creation of Chains objects. But once created, we only use Symbols (I at least). It is an inconvenience when one wants to use ```a[1]``` or ```a.1``` as Symbols but in above NamedTuple format we step around that.

In SR I have renamed the above function to:
```
import Core.Array

function Array(chn::MCMCChains.AbstractChains)
  local a
  for (i, par) in enumerate(names(chn))
    x = get(chn, Symbol(par))
    d, c = size(x[Symbol(par)])
    if i == 1
      a = reshape(convert(Array{Float64}, x[Symbol(par)]), d*c)[:, 1]
    else
      a = hcat(a, reshape(convert(Array{Float64}, x[Symbol(par)]), d*c)[:, 1])
    end
  end
  a
end
```
The 2 keyword arguments I'm thinking about are ```remove_missing=true``` and ```append=true```. 

Setting the first option to ```false``` would remove the convert() encapsulations.

Setting the second option to ```false``` would remove the reshape() encapsulations (and return a Vector{Array}?). 

A third refinement is to assign the columns the correct type (Float64, Int64, ....). The Array would then be type ```Array{Any, 2}``` (which might affect code optimizations?).

**Comment by cpfiffer** [comment]
>Currently Stings are used in MCMCChains during the creation of Chains objects. But once created, we only use Symbols (I at least). It is an inconvenience when one wants to use `a[1]` or `a.1` as Symbols but in above NamedTuple format we step around that.

I think we should be careful about the symbol/string dichotomy. We support a _lot_ of symbol support, but ultimately strings are really the names of parameters. We just support a bunch of extra features if you're indexing by symbols I think mostly for historical reasons. Turing tends to make a ton of columns if you have matrix valued parameters or whatever.

As to the `Array` function, I like both the keyword arguments you've got. `Vector{Array}` would probably make sense for `append=false`, I think. 

> A third refinement is to assign the columns the correct type `(Float64, Int64, ....)`. The Array would then be type `Array{Any, 2} `(which might affect code optimizations?).

If we can enforce column typing then that'd be super cool. I'm not exactly the optimization police however, so I don't know that I can intelligently speak to the performance effects.

**Comment by goedman** [comment]
I fully agree that we shouldn't go too far. It is interesting that you see using symbols as historical. I see that as the `proper` way, but it was just never available in most programming languages!

Anyway, what I was trying to express is that whatever we come up with is consistent to the end user, not sometimes strings and other times symbols.

I'll further experiment with the Array constructor.

**Comment by mkborregaard** [comment]
> I see [symbols] as the proper way, but it was just never available in most programming languages!

I agree with this. Symbols are more ideomatic

**Comment by cpfiffer** [comment]
I suppose I mostly view them as sometimes troublesome because of how Turing packages indexed parameters. If I've got a vector `x = Vector{Float64, 10}`, I'll have ten separate parameters `"x[1]"`, `"x[2]"` and so on. I don't like getting those with symbols because it's easier to type `chn["x[1]"]` than it is to do `chn[Symbol("x[1]")]`. I think I've got an idea to fix this so it's not such a big deal, but it needs a little more thought. 

So yeah, I really like symbols if it's something like `:param1`, but I'm mostly just frustrated with how Turing's parameter names come out.

**Comment by goedman** [comment]
That's not just Turing. Stan and Mamba are similar. DynamicHMC has the solution we discussed earlier:
```
[
(alpha=2.401, beta=[0.41, 0.23, 1.14), sigma=3.42),
(alpha=2.392, beta=[0.39, 0.21, 1.16), sigma=3.50),
(alpha=2.398, beta=[0.38, 0.22, 1.21), sigma=3.52),
...
]
```
which is easy to convert to ```beta[1]``` etc by simple comprehensions for output. But occasionally it will force you to specify ```Symbol("beta[1]")``` in MCMCChains.

The more we discuss this the more I like this format and together with NamedTupleTools.jl (e.g. conversion to and fro Dicts) and Parameters.jl (e.g. @unpack) it would be a solid basis. I'll experiment a bit more with this and compare it with the Array approach.

Did you see [Chris Fisher's post](https://discourse.julialang.org/t/extracting-summary-info-from-multiple-mcmcchains-programmatically/22027?u=goedman) on Discourse?

**Comment by goedman** [comment]
Hi Cameron,

After some experimenting I came up with below Array() constructor and associated test code:
```
using MCMCChains, Test
import Core.Array

function Array(chn::MCMCChains.AbstractChains;
  append_chains=true, remove_missing_union=true)
  a = remove_missing_union ? convert(Array{Real, 3}, chns.value.data) : chns.value.data
  d, p, c = size(a)
  if append_chains
    b = vcat((a[:,:, i] for i in 1:c)...)
  else
    b=Vector{Array{Union{Missing, Real},2}}(undef, c)
    for i in 1:c
      b[i] = a[:, :, i]
    end
  end
  return b
end  

@testset "Array constructor tests" begin
  
  d = 5; p = 3; c = 2
  
  a3d = Array{Union{Missing, Real}, 3}(undef, d, p, c)
  a3d[:, 1, 1] = rand(d)
  a3d[:, 2, 1] = sample(1:5, d)
  a3d[:, 3, 1] = sample([true, false], d)

  a3d[:, 1, 2] = rand(d)
  a3d[:, 2, 2] = sample(1:5, d)
  a3d[:, 3, 2] = sample([true, false], d)

  chns = MCMCChains.Chains(a3d, start=1, thin=1)

  @test size(Array(chns)) == (d*c, p)
  @test size(Array(chns, append_chains=true)) == (d*c, p)
  @test size(Array(chns, append_chains=false)) == (2,)
  @test size(Array(chns, append_chains=false)[1]) == (d, p)
  @test typeof(Array(chns, append_chains=true)) == Array{Real, 2}
  @test size(Array(chns, remove_missing_union=false)) == (d*c, p)
  @test size(Array(chns, append_chains=false, remove_missing_union=false)) == (2,)
  @test size(Array(chns, append_chains=false, remove_missing_union=false)[1]) == (d, p)
  @test typeof(Array(chns, append_chains=true, remove_missing_union=false)) == 
    Array{Union{Missing, Real}, 2}

  Array(chns)
end
```

For now I have just added it to StatisticalRethinking (like I did with the sampling), but if we decide to incorporate it in some form in MCMCChains I'll remove it (as MCMCChains is now an integral part of both CmdStan - in the upcoming v5.0.0 release - and StatisticalRethinking).

I'm not sure if it is possible to incorporate the 3rd refinement (where the array constructor assigns concrete types to the columns) as chains.value.data is typed as Union{Missing, Real}.

Wanna experiment a bit more with the Vector{NamedTuple} approach next because if something like get_params() would return that, NamedTupleTools.jl give the end users a range of options.

**Comment by cpfiffer** [comment]
> Did you see Chris Fisher's post on Discourse?

Thanks for mentioning that to me, I would have missed that entirely.

> which is easy to convert to `beta[1]` etc by simple comprehensions for output. But occasionally it will force you to specify `Symbol("beta[1]")` in MCMCChains.

Yeah, though I think we can set this up to take the bracket indexing from the symbols and build it into the `NamedTuple` structure. I started to do something like this before with `get` but it only works for single-level indexing. I'd love to have some weird matrix as a parameter in Turing that unwraps each value to `x[1,1,1]`, `x[1,1,2]`, and then have this `NamedTuple` row function return something that allows you to replicate that indexing structure. 

As an example, I'd like `get_params` or something to return a `NamedTuple` `nt` where `nt.x[1,1,1
]` can be used to retrieve that first argument. 

I like your array constructor, and I'll probably sit down with it sometime to get it incorporated into Turing.

**Comment by goedman** [comment]
Can't you do that right now (maybe I'm missing a subtlety):
```
julia> nt = (a=[1,2], b=[1 2;3 4],)
(a = [1, 2], b = [1 2; 3 4])

julia> nt.b
2×2 Array{Int64,2}:
 1  2
 3  4

julia> nt.b[1,2]
2
```

What I've never been able to really figure out is how to do that after the fact. I think Turing must know this structure, but can we come up with a rock solid transformation to a NamedTuple. I've always wanted to do that using cmdstan's output (which is a pretty poor .csv file) but but never had the guts to go there.

I know you are busy, but if we want to pursue this we should maybe study Tamas Papp's [TransformVariables.jl](https://github.com/tpapp/TransformVariables.jl), in particular his as() functions.

Just out of curiosity, why would you consider moving the Array constructor to Turing.jl and not leave it in MCMCChains.jl? The idea behind it (al least in my thinking) is that, over time, MCMCChains covers more and more the functionality as in R's bayesplot. But for users to quickly experiment beyond that they can convert to an Array and just play around.

**Comment by cpfiffer** [comment]
You can do that in a `NamedTuple`, but MCMCChains doesn't really have a good system for "repackaging" split parameters at the moment. I would like it to be pretty much automatic for whatever `get_params` or `NamedTupleArray` functions we have to do that if your chain has some indexed values, so that you never have to do `x.Symbol("param[1]")` and instead you can just do `x.param[1]`. One of these days I'll put up a formal issue laying out my thoughts a little better.

> What I've never been able to really figure out is how to do that after the fact. I think Turing must know this structure, but can we come up with a rock solid transformation to a NamedTuple. I've always wanted to do that using cmdstan's output (which is a pretty poor .csv file) but but never had the guts to go there.

We have a function Turing-side that takes some weird parameter name like `"x[1,1][2,15]"` and returns the indices and the variable symbol. It looks something like

```julia
varname_str = "x[1,1][2,15]"
unvarname(varname_str)
```

Output:
```
("x", Array{String,1}[["1", "1"], ["2", "15"]])
```

This could be ported over here and used to package up any "bracketed" parameter name really nicely into a `NamedTuple`.

> I know you are busy, but if we want to pursue this we should maybe study Tamas Papp's TransformVariables.jl, in particular his as() functions.

I like them! Maybe a good syntax in our case would be something like `as(Array, chn)` and `as(Array, NamedTuple)`?

> Just out of curiosity, why would you consider moving the Array constructor to Turing.jl and not leave it in MCMCChains.jl? The idea behind it (al least in my thinking) is that, over time, MCMCChains covers more and more the functionality as in R's bayesplot. But for users to quickly experiment beyond that they can convert to an Array and just play around.

Woops! I mis-typed that. I meant to say MCMCChains but I have Turing on the brain.

**Comment by goedman** [comment]
Cool, ok if I let this part sit with you for a while?

For StatisticalRethinking, and mcmc in general, I want to take a closer look at R's [bayesplots](http://mc-stan.org/bayesplot/articles/graphical-ppcs.html) and compare it where we are with StatsPlots ( @mkborregaard , just fyi). Above link is in the area of PPC, but the other 2 vignettes are also very good.

**Comment by mkborregaard** [comment]
I bet there are a lot of cool recipes we could write based on bayesplots.

**Comment by goedman** [comment]
You bet! Now MCMCChains v0.3.5 is released I'll go back to StatisticalRethinking and the bayesplot comment.
