### ISSUE TITLE
Sampling capability for posterior predictive distributions

### ISSUE THREAD

**Issue by fisherc2** [TuringLang/MCMCChains.jl#66]
Currently, MCMCChains does not have built in functions for sampling posterior values from chain objects. As discussed on [discourse](https://discourse.julialang.org/t/posterior-predictive-distributions-in-turing/21781/5), having a sampling function or framework could be useful for generating posterior predictive distributions.

**Comment by cpfiffer** [comment]
Yeah, I think that'd get us a long way. I made a couple changes, like using `range(chn)` instead of `1:size(chn, 1)`, since we allow for chains to have custom ranges. I also changed `Chains(chn.value[indxs, :, :], names(chn), chn.name_map)` to just `return chn[indxs, :, :]`.

```julia
import StatsBase: sample
using Random

# sample([rng], a, [wv::AbstractWeights], n::Integer; replace=true, ordered=false)
function sample(rng::AbstractRNG, chn::MCMCChains.AbstractChains, n;
    replace=true, ordered=false) 
  indxs = sample(rng,range(chn), n,
    replace=replace, ordered=ordered)
  return chn[indxs, :, :]
end

function sample(chn::MCMCChains.AbstractChains, n;
    replace=true, ordered=false) 
  indxs = sample(Random.GLOBAL_RNG, range(chn), n,
    replace=replace, ordered=ordered)
  return chn[indxs, :, :]
end
```

Should this return an array or something instead of a `Chains` object? I'm never sure when it is we should return numeric values vs. a chain.

**Comment by goedman** [comment]
Hmm, thought I started off with your last improvement. But this is great.

My suggestion is to return a chain mainly because of the next step, weighted sampling for posterior sampling, where we might want to work with 10000 samples vs. maybe just 1000 mcmc draws. 

The other reason is related to my response to the other issue (Expand Utility Function), I suggest for now we stick to a rule like turning a chain into numerical values is the last step. We export at that point `out of MCMCChains`. This also preserves consistency and all nice plotting and selection capabilities.

I'll add the weight factors in a similar fashion today.

**Comment by goedman** [comment]
Cameron, I'm using this test program:
```
using StatisticalRethinking
import StatsBase: sample

ProjDir = @__DIR__
cd(ProjDir)

include("../test/samplechain.jl")

describe(chn)

df = to_df(chn)

df_sample = sample(df, 5)
display(df_sample)
println()

chn_sample = sample(chn, 5)
display(chn_sample)
println()

s = kde(df[:sigma])
#plot(s.x, s.density)

c = kde(par_to_array(chn, :sigma))
#plot!(c.x, c.density)

chn_weighted_sample = sample(chn, Weights(c.density), 10000)
display(chn_weighted_sample)
println()
```
and I think it fails with the new return format ( ```return chn[indxs, :, :]``` ). In my case I use a simple, 3 parameter CmdStan chain, but we could probably use @model gdemo (although it is nice to have a sigma in there because the density is not normal).

**Comment by cpfiffer** [comment]
Not sure why it's failing, do you have the error code on that?

**Comment by goedman** [comment]
Apologies, I'll have a look, simply assumed you would immediately point out why.

**Comment by goedman** [comment]
Can you run this MWE? 
```
using Turing, Random
import StatsBase: sample

function sample(chn::MCMCChains.AbstractChains, n;
    replace=true, ordered=false) 
  indxs = sample(Random.GLOBAL_RNG, range(chn), n,
    replace=replace, ordered=ordered)
  return chn[indxs, :, :]
  #return Chains(chn.value[indxs, :, :], names(chn), chn.name_map)
end

@model gdemo(x) = begin
    s ~ InverseGamma(2,3)
    m ~ Normal(0, sqrt(s))
    for i in eachindex(x)
        x[i] ~ Normal(m, sqrt(s))
    end
end

model = gdemo([1.5, 2.0])
sampler = HMC(500, 0.01, 5)
chn = sample(model, sampler, save_state=true)
describe(chn)

chn_sample = sample(chn, 5)
chn_sample
```

If you move the '#' to the other return in sample() it will fail:
```
ERROR: MethodError: no method matching step(::Array{Int64,1})
Closest candidates are:
  step(::StepRange) at range.jl:499
  step(::AbstractUnitRange{T}) where T at range.jl:500
  step(::StepRangeLen{T,R,S} where S where R) where T at range.jl:501
  ...
```

**Comment by cpfiffer** [comment]
> Apologies, I'll have a look, simply assumed you would immediately point out why.

I appreciate your misplaced confidence!

Your version was much better. The only thing missing was bringing in the `chn.info` field, which we may or may not need. I've changed it to this:

```julia
function sample(chn::MCMCChains.AbstractChains, n;
    replace=true, ordered=false)
  indxs = sample(Random.GLOBAL_RNG,
    range(chn),
    n,
    replace=replace, ordered=ordered)
  return Chains(chn.value[indxs, :, :],
    names(chn),
    chn.name_map,
    info = chn.info)
end
```

**Comment by goedman** [comment]
Cool. I'll make a PR including the sampling with a Weights vector.

The logevidence, is that the average probability of the data (normalizing factor)? Is it generally inserted by the samplers? Should it be part of a chain summary (no strong feelings but the field often seems 0.0, at least for NUTS, maybe it is similar to the info field for continuation)?

**Comment by cpfiffer** [comment]
> The logevidence, is that the average probability of the data (normalizing factor)? Is it generally inserted by the samplers? Should it be part of a chain summary (no strong feelings but the field often seems 0.0, at least for NUTS, maybe it is similar to the info field for continuation)?

Yes, it's usually inserted the samplers, and I think it's the marginal evidence/log model evidence. Not sure on that, though. I think maybe importance sampling, particle Gibbs, SMC, and maybe a couple others use it. I think we can probably adapt the header function to only show the log evidence if it's non-zero without too much trouble. I've opened an issue to remind myself to fix it (#69).

**Comment by goedman** [comment]
Chris ( @fisherc2 ) the sampling API is now part of MCMCChains 0.3.5. I'll close this issue for now but let us know if you find any issues!

**Comment by fisherc2** [comment]
Thanks to you both!
