### ISSUE TITLE
Only print the logevidence field if it is non-zero

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/MCMCChains.jl#69]
Currently the `header(chn)` function prints the `logevidence` field always, which is quite annoying if you only ever sample with things that don't return log evidence. 

`header(chn)` should only print `logevidence` if it is nonzero.

**Comment by goedman** [comment]
Definitely a good solution. Nonzero or Missing?

**Comment by cpfiffer** [comment]
Not sure. The constructor enforces 0.0 as the `logevidence`, but maybe that shouldn't be the case. Do you have a preference?

**Comment by goedman** [comment]
Slight preference for it to be Missing. And can be tested by ismissing().

Don't think log evidence should ever get too close to 0.0 (as it is typically in the denominator).

**Comment by cpfiffer** [comment]
Closed by #70.
