### ISSUE TITLE
Make chain summaries easier to extract and store

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/MCMCChains.jl#71]
Hi-

I am opening this issue based on a discussion in [discourse](https://discourse.julialang.org/t/extracting-summary-info-from-multiple-mcmcchains-programmatically/22027/5).  The current problem is that summary information is difficult to extract from the chain programmatically in large scale simulations. The current solution is to use StatsBase and extract from the chain's nested structure:

```
using StatsBase

function getSummary(ch)
    chain = ch[1001:end,:,:]
    return summarystats(chain).summaries[1].value
end
```

So the question is whether there is a simpler way for the user to work with summary data.

**Comment by goedman** [comment]
Cameron, I have been wondering about [Tables.jl](https://github.com/JuliaData/Tables.jl). Of course yet another dependency. It provides an Array with named rows and columns. The parameters could be the rows, the statistics (mean, sd, ...) the columns. I've never worked with this package and would like to check if we can enable stuff like get(table, [:alpha, :beta], [:mean, sd]).

**Comment by cpfiffer** [comment]
Tables does seem to be low-level enough and a fairly small dependency, so it might be advantageous to use. Plus, having easily modifiable columns would allow use to get rid of `Showoff` which I'm not a big fan of.

**Comment by goedman** [comment]
Yes, although I'm not sure with Tables we get a lot of benefits in terms of printout/format support. It would be nice to get that for free. The other option is just DataFrames with a 1st column of Symbols. How would you feel about that? 

In that case, like the Array proposal, we can also support exporting chains as a DataFrame.

In fact, I'll make a pull request that contains both (Arrays and DataFrames) to play around with. I have added one more aspect to the Array constructor. If you export a single parameter the output format is collapsed into a vector, e.g. kde requires that. In a sense Arrays and DataFrames are nicely complementary.

**Comment by mkborregaard** [comment]
DataFrames depends on Tables, so. IMHO DataFrames is a good implementation for object-internal storage, but for input arguments it's better to use the Tables interface than to require users to have their stuff in DataFrames.

**Comment by goedman** [comment]
To make sure I understand your comment correctly Michael, the proposed usage is that after running an mcmc simulation, MCMCChains creates this table with results once and stores it, e.g. show() would simply display the table. In some cases folks would like to be able to programmatically read a few fields, e.g. for tests in runtests.jl or, as Chris might use it, to compare many mcmc runs programmatically. I see it as output only, not for user input. 

The second part of this discussion is to give end-users a simpler, more familiar maybe, option to further experiment with mcmc chains where Cameron and I have talked about an Array constructor and above I suggest to also provide an option to convert chains to the DataFrame format.

**Comment by mkborregaard** [comment]
Thanks @goedman both of those make sense to me. I believe the Tables jl is primarily relevant in terms of dealing with user input.

**Comment by goedman** [comment]
@cpfiffer Hi Cameron, I've made a first stab at a DataFrame based chain summary feature. Do you mind taking a look. It's in the branch `dfchainsummary`. 

At least 2 questions remain:

1. We need to come up with a nice api the query summary values. Currently:
```
julia>   parm_df = dfchainsummary(chns, [:parameters])
2×6 DataFrame
│ Row │ parameters │ mean    │ std       │ naive_se    │ mcse        │ ess   │
│     │ Symbol     │ Float64 │ Float64   │ Float64     │ Float64     │ Int64 │
├─────┼────────────┼─────────┼───────────┼─────────────┼─────────────┼───────┤
│ 1   │ m          │ 1.00029 │ 0.0147124 │ 0.000232624 │ 0.000397133 │ 4000  │
│ 2   │ s          │ 4.99359 │ 0.126117  │ 0.00199409  │ 0.00329054  │ 4000  │


julia> parm_df[parm_df.parameters .== :m, :mean]
1-element Array{Float64,1}:
 1.0002915522800457
```

Maybe we could have something like `get_stat(parm_df, :alpha, :mean)`?

2. Do we generate the summary by default as a Chains object is created and store it in a new field (missing if not previously generated)? By default it will show all observed variables:
```
julia>   all_df = dfchainsummary(chns)
8×6 DataFrame
│ Row │ parameters │ mean        │ std         │ naive_se    │ mcse        │ ess   │
│     │ Symbol     │ Float64     │ Float64     │ Float64     │ Float64     │ Int64 │
├─────┼────────────┼─────────────┼─────────────┼─────────────┼─────────────┼───────┤
│ 1   │ m          │ 1.00029     │ 0.0147124   │ 0.000232624 │ 0.000397133 │ 4000  │
│ 2   │ s          │ 4.99359     │ 0.126117    │ 0.00199409  │ 0.00329054  │ 4000  │
│ 3   │ elapsed    │ 0.000235103 │ 0.00776922  │ 0.000122842 │ 0.000122504 │ 4000  │
│ 4   │ epsilon    │ 0.01        │ 3.46988e-18 │ 5.48636e-20 │ 0.0         │ 4000  │
│ 5   │ eval_num   │ 6.995       │ 0.158055    │ 0.00249906  │ 0.00240192  │ 4000  │
│ 6   │ lf_eps     │ 0.01        │ 3.46988e-18 │ 5.48636e-20 │ 0.0         │ 4000  │
│ 7   │ lf_num     │ 4.995       │ 0.158055    │ 0.00249906  │ 0.00240192  │ 4000  │
│ 8   │ lp         │ -73.423     │ 2112.56     │ 33.4025     │ 41.7008     │ 4000  │
```
Just a first stab ...

**Comment by cpfiffer** [comment]
I like it! I'd been working on something similar, and seeing how various methods worked with `NamedArray`, `DataFrame`, and `NamedTuple` types. 

> Do we generate the summary by default as a Chains object is created and store it in a new field (missing if not previously generated)? By default it will show all observed variables:

No, it shouldn't be generated by default. It should only be generated when specifically requested by the user, so we're not doing needless computation and carrying stuff around.

As to the rest of it, my only problem with the dataframe format is that it truncates rows when called by `display`. For example, just making the summary for one of our higher-dimensional models gets this:

```julia
df = dfchainsummary(chn)
```
Output:
```
12×6 DataFrame
│ Row │ parameters │ mean     │ std         │ naive_se    │ mcse        │ ess   │
│     │ Symbol     │ Float64  │ Float64     │ Float64     │ Float64     │ Int64 │
├─────┼────────────┼──────────┼─────────────┼─────────────┼─────────────┼───────┤
│ 1   │ z3         │ 2.0      │ 0.0         │ 0.0         │ 0.0         │ 500   │
│ 2   │ z1         │ 2.0      │ 0.0         │ 0.0         │ 0.0         │ 500   │
│ 3   │ mu2        │ 2.55357  │ 1.77814e-15 │ 7.95207e-17 │ 0.0         │ 500   │
│ 4   │ z2         │ 1.0      │ 0.0         │ 0.0         │ 0.0         │ 500   │
⋮
│ 8   │ epsilon    │ 0.01     │ 3.47292e-18 │ 1.55314e-19 │ 0.0         │ 500   │
│ 9   │ eval_num   │ 2.0      │ 0.0         │ 0.0         │ 0.0         │ 500   │
│ 10  │ lf_eps     │ 0.01     │ 3.47292e-18 │ 1.55314e-19 │ 0.0         │ 500   │
│ 11  │ lf_num     │ 0.0      │ 0.0         │ 0.0         │ 0.0         │ 500   │
│ 12  │ lp         │ -13.0525 │ 1.77814e-15 │ 7.95207e-17 │ 8.88178e-16 │ 500   │
```

While calling `println(df)` gives me this (which is what I want by default):
```
12×6 DataFrame
│ Row │ parameters │ mean        │ std         │ naive_se    │ mcse        │ ess   │
│     │ Symbol     │ Float64     │ Float64     │ Float64     │ Float64     │ Int64 │
├─────┼────────────┼─────────────┼─────────────┼─────────────┼─────────────┼───────┤
│ 1   │ z3         │ 2.0         │ 0.0         │ 0.0         │ 0.0         │ 500   │
│ 2   │ z1         │ 2.0         │ 0.0         │ 0.0         │ 0.0         │ 500   │
│ 3   │ mu2        │ 2.55357     │ 1.77814e-15 │ 7.95207e-17 │ 0.0         │ 500   │
│ 4   │ z2         │ 1.0         │ 0.0         │ 0.0         │ 0.0         │ 500   │
│ 5   │ z4         │ 2.0         │ 0.0         │ 0.0         │ 0.0         │ 500   │
│ 6   │ mu1        │ 0.350978    │ 0.0         │ 0.0         │ 0.0         │ 500   │
│ 7   │ elapsed    │ 0.000249823 │ 1.08529e-19 │ 4.85356e-21 │ 0.0         │ 500   │
│ 8   │ epsilon    │ 0.01        │ 3.47292e-18 │ 1.55314e-19 │ 0.0         │ 500   │
│ 9   │ eval_num   │ 2.0         │ 0.0         │ 0.0         │ 0.0         │ 500   │
│ 10  │ lf_eps     │ 0.01        │ 3.47292e-18 │ 1.55314e-19 │ 0.0         │ 500   │
│ 11  │ lf_num     │ 0.0         │ 0.0         │ 0.0         │ 0.0         │ 500   │
│ 12  │ lp         │ -13.0525    │ 1.77814e-15 │ 7.95207e-17 │ 8.88178e-16 │ 500   │
```

I wonder if we could make a wrapper struct like 

```julia
struct ChainDataFrame
   df::DataFrame
end
```

This would help with the indexing issue by allowing us to overwrite the indexing, so we could do stuff like `df[:z1, :mean]` and `df[[:z1, z3], :mean]`, etc.

I've written the following to tack onto your `dfchainsummary.jl` file if you like the above format (totally fine if you don't, which is why I haven't committed this to your branch). Still quite preliminary, but it should handle most of the indexing problems you highlighted.

```julia
struct ChainDataFrame
    df::DataFrame
end

Base.show(io::IO, c::ChainDataFrame) = show(io, c.df)

Base.getindex(c::ChainDataFrame, args...) = getindex(c.df, args...)
Base.getindex(c::ChainDataFrame, s::Union{Symbol, Vector{Symbol}}) = return c.df[s]

function Base.getindex(c::ChainDataFrame,
        s1::Vector{Symbol},
        s2::Union{Symbol, Vector{Symbol}})
    return c.df[map(x -> x in s1, c.df.parameters), s2]
end

function Base.getindex(c::ChainDataFrame,
        s1::Symbol,
        s2::Union{Symbol, Vector{Symbol}})
    return c.df[c.df.parameters .== s1, s2]
end

function dfchainsummary(chn::MCMCChains.AbstractChains,
  sections::Vector{Symbol}=Symbol[]; etype=:bm, args...)

  sem(x) = sqrt(var(x) / length(x))
  df_mcse(x) = mcse(x, etype, args...)

  df = DataFrame(chn, sections)

  # Add summary stats columns
  if size(chn.value, 1) > 200
    sum_df = DataFrame(
      :parameters => names(df),
      :mean => colwise(mean, df),
      :std => colwise(std, df),
      :naive_se => colwise(sem, df),
      :mcse => colwise(df_mcse, df),
      :ess => repeat([size(df, 1)], length(names(df)))
    )
  else
    sum_df = DataFrame(
      :parameters => names(df),
      :mean => colwise(mean, df),
      :std => colwise(std, df),
      :naive_se => colwise(sem, df)
    )
  end

    return ChainDataFrame(sum_df)
end
```

**Comment by goedman** [comment]
Agreed, we shouldn't generate the dfchainsummaries by default.

DataFrames have options for display:
```
Printing options can be adjusted by calling the show function manually: show(df, allrows=true) prints all rows even if they do not fit on screen and show(df, allcols=true) does the same for columns.
```
Great addition to use the wrapper type!  Go ahead and add it!

**Comment by goedman** [comment]
What do you think about adding a few more (in addition to getindex) 'typical' Chains methods, such as names() and size()?

**Comment by cpfiffer** [comment]
Done, I've added those to the branch. I've also added a `summarize` function, which takes the given functions and runs them through each parameter. Usage:

```julia
# Pass in some vector-valued functions.
summarize(chn, mean, var)
```

```
6×3 DataFrame
│ Row │ parameters │ mean     │ var         │
│     │ Symbol     │ Float64  │ Float64     │
├─────┼────────────┼──────────┼─────────────┤
│ 1   │ mu1        │ 0.741109 │ 4.94026e-32 │
│ 2   │ mu2        │ 1.73122  │ 4.94026e-32 │
│ 3   │ z1         │ 1.0      │ 0.0         │
│ 4   │ z2         │ 2.0      │ 0.0         │
│ 5   │ z3         │ 2.0      │ 0.0         │
│ 6   │ z4         │ 2.0      │ 0.0         │
```

```julia
# Use the default summary statistics if no functions are provided.
summarize(chn)
```
```
6×6 DataFrame
│ Row │ parameters │ mean     │ std         │ naive_se    │ mcse        │ ess     │
│     │ Symbol     │ Float64  │ Float64     │ Float64     │ Float64     │ Float64 │
├─────┼────────────┼──────────┼─────────────┼─────────────┼─────────────┼─────────┤
│ 1   │ mu1        │ 0.741109 │ 2.22267e-16 │ 9.94008e-18 │ 0.0         │ 500.0   │
│ 2   │ mu2        │ 1.73122  │ 2.22267e-16 │ 9.94008e-18 │ 1.11022e-16 │ 4.00802 │
│ 3   │ z1         │ 1.0      │ 0.0         │ 0.0         │ 0.0         │ NaN     │
│ 4   │ z2         │ 2.0      │ 0.0         │ 0.0         │ 0.0         │ NaN     │
│ 5   │ z3         │ 2.0      │ 0.0         │ 0.0         │ 0.0         │ NaN     │
│ 6   │ z4         │ 2.0      │ 0.0         │ 0.0         │ 0.0         │ NaN     │
```

The above `summarize(chn)` call falls back on a new function `dfsummarystats`, which is pretty much identical to the function you wrote, except it calls `summarize(chn)` with the functions we'd normally pass in. You can call that directly using `dfsummarystats(chn, [:parameters])`, which returns the following:

```
6×6 DataFrame
│ Row │ parameters │ mean     │ std         │ naive_se    │ mcse        │ ess     │
│     │ Symbol     │ Float64  │ Float64     │ Float64     │ Float64     │ Float64 │
├─────┼────────────┼──────────┼─────────────┼─────────────┼─────────────┼─────────┤
│ 1   │ mu1        │ 0.741109 │ 2.22267e-16 │ 9.94008e-18 │ 0.0         │ 500.0   │
│ 2   │ mu2        │ 1.73122  │ 2.22267e-16 │ 9.94008e-18 │ 1.11022e-16 │ 4.00802 │
│ 3   │ z1         │ 1.0      │ 0.0         │ 0.0         │ 0.0         │ NaN     │
│ 4   │ z2         │ 2.0      │ 0.0         │ 0.0         │ 0.0         │ NaN     │
│ 5   │ z3         │ 2.0      │ 0.0         │ 0.0         │ 0.0         │ NaN     │
│ 6   │ z4         │ 2.0      │ 0.0         │ 0.0         │ 0.0         │ NaN     │
```

I think it'll be pretty easy to just call `summarize` to translate the rest of the built-in summary statistic functions.

**Comment by goedman** [comment]
Much better approach!

**Comment by goedman** [comment]
Are we consistent with the use of the keyword none/section/sections? Right now I think
```
Chains(..., :internals) or Chains(..., [:parameters, :internals])
describe(chns, section=:internals)
summarize(chns, sections=[:parameters, :internals])
hpd(chn::AbstractChains; alpha::Real=0.05,
    showall=false, suppress_header=false, section=:parameters)
```
Maybe it should always be an optional keyword arguments expecting a Vector and with a default of [:parameters]?

**Comment by cpfiffer** [comment]
Yeah, let's shoot to use `sections = Vector{Symbol}[:parameters]` as the default.

**Comment by goedman** [comment]
Great! 

Just for my education, how hard is it to make something like `ChainDataFrame` an iterator. I've experimented a bit with:
```
using MCMCChains, DataFrames, Query
y = @from i in parm_df.df begin
    @where i.parameters in [:alpha, :beta, :sigma]
    @select {i.mean, i.std}
    @collect DataFrame
end
```
and was just wondering if there too it is possible to get rid of the one level of indirections (part_df.df).

**Comment by cpfiffer** [comment]
From what I remember it's pretty straightforward, there's only a couple functions we need to wrap around. I can implement it the next time I sit down with this.

**Comment by goedman** [comment]
Hi Cameron,

On Julia 1.2 the creation of func_names fails. I replaced it by:
```
    # If no function names were given, make a new list.
    func_names = length(func_names) == 0 ?
        Symbol.([f for f in funs]) : Symbol.(func_names)
```
but that returns on Julia 1.1:
```

julia> summarize(chns, mean, std)
3×3 DataFrame
│ Row │ parameters │ Statistics.mean │ Statistics.std │
│     │ Symbol     │ Float64         │ Float64        │
├─────┼────────────┼─────────────────┼────────────────┤
│ 1   │ alpha      │ 154.595         │ 0.271168       │
│ 2   │ beta       │ 0.906153        │ 0.041679       │
│ 3   │ sigma      │ 5.10449         │ 0.194403       │

```
I'll experiment a bit more.

**Comment by goedman** [comment]
Thanks for offering, but let's finish the must-do items first and merge & release #71 and #75 fixes?

**Comment by cpfiffer** [comment]
By the #71 fix, you mean the `dfchainsummary` branch, right?

**Comment by goedman** [comment]
Yip!

**Comment by cpfiffer** [comment]
Do you have a good idea on what to do in the case of a `Chains` object with multiple chains in it? The current `ChainSummary` will report separate tables for each chain. Perhaps we should return a vector of `ChainDataFrames`, with one frame for each chain?

**Comment by goedman** [comment]
In Array and DataFrame by default I append the chains (`append_chains=true`). I think this covers by far the majority of useful usage. If folks want to see the summary for each chain, we can return an array of Arrays, DataFrames and Chain summaries (`append_chains=false`)?

**Comment by goedman** [comment]
Chris, I’ll close this for now. Please let us know if the ChainDataFrame based solution works for you.
