### ISSUE TITLE
quantiles from describe not matching quantiles when MCMC chains extracted first.

### ISSUE THREAD

**Issue by tszanalytics** [TuringLang/MCMCChains.jl#75]
Computing quantiles by first converting the chain to an Array then using quantiles provides a narrower interval than the describe function.  A plot of the chain suggests that the narrower interval is the correct one.

describe(chain[200:end,:,:])
Quantiles
─────────────────────────────────────────────────────────
parameters
                2.5%    25.0%    50.0%    75.0%    97.5%
KappaMinusTwo 23.8318 116.7405 151.3484 192.5131 499.6650
     theta[1]  0.0749   0.1728   0.1973   0.2262   0.4725
     theta[2]  0.0557   0.1529   0.1754   0.1992   0.3252
     theta[3]  0.0985   0.1782   0.2011   0.2243   0.3579
     theta[4]  0.0906   0.1557   0.1722   0.1899   0.2871
     theta[5]  0.0460   0.1039   0.1187   0.1344   0.2038
            w  0.0926   0.1526   0.1682   0.1851   0.2980

quantile(Array(chain[:, "w", :]), [0.025, 0.5, 0.975]) 
= [0.124264, 0.16864, 0.223697]

quantile(Array(chain[200:end, "w", :]), [0.025, 0.5, 0.975]) 
= [0.124743, 0.168218, 0.221467]

![MCMC_chains_w](https://user-images.githubusercontent.com/28225301/55352480-ec6a7600-548e-11e9-8f2c-d8e18a5f4d81.png)

**Comment by goedman** [comment]
Looks like something is indeed wrong. This is a simple CmdStan result showing the same problem:
```

julia> quantile(Array(chns[:alpha]), [0.025, 0.25, 0.5, 0.75, 0.975])
5-element Array{Float64,1}:
 154.063975
 154.413   
 154.594   
 154.768   
 155.104   

julia> quantile(Array(chns[:beta]), [0.025, 0.25, 0.5, 0.75, 0.975])
5-element Array{Float64,1}:
 0.819244675       
 0.8757625         
 0.904451          
 0.93357625        
 0.9867265749999999

julia> quantile(Array(chns[:sigma]), [0.025, 0.25, 0.5, 0.75, 0.975])
5-element Array{Float64,1}:
 4.7513215 
 4.9785825 
 5.104225  
 5.2365    
 5.47546475

julia> describe(chns)
Iterations        = 1:1000
Thinning interval = 1
Chains            = 1, 2, 3, 4
Samples per chain = 1000
parameters        = alpha, beta, sigma

Empirical Posterior Estimates
──────────────────────────────────────────────────
parameters
        Mean     SD   Naive SE  MCSE   ESS
alpha 154.5903 0.2647   0.0042 0.0038 1000
 beta   0.9045 0.0430   0.0007 0.0006 1000
sigma   5.1090 0.1872   0.0030 0.0033 1000

Quantiles
──────────────────────────────────────────────────
parameters
        2.5%     25.0%    50.0%    75.0%    97.5% 
alpha 153.6650 154.4130 154.5940 154.7680 155.5450
 beta   0.7324   0.8758   0.9045   0.9336   1.0476
sigma   4.5206   4.9786   5.1042   5.2365   5.7675

```

**Comment by goedman** [comment]
There is a weird weighing vector defined in the quantile function in stats.jl:
```
    # Quantile weights.
    #w = [0.0, 0.25, 0.5, 0.75, 1.0]
    w = [0.025, 0.25, 0.5, 0.75, 0.975]
```
I really don't understand what the old (commented out) values of w do, but if I replace it by the w  = [0.025, 0.25, 0.5, 0.75, 0.975] (now w == q), I get:

```
julia> describe(chns)
Iterations        = 1:1000
Thinning interval = 1
Chains            = 1, 2, 3, 4
Samples per chain = 1000
parameters        = alpha, beta, sigma

Empirical Posterior Estimates
──────────────────────────────────────────────────
parameters
        Mean     SD   Naive SE  MCSE   ESS
alpha 154.5960 0.2651   0.0042 0.0046 1000
 beta   0.9058 0.0434   0.0007 0.0008 1000
sigma   5.0985 0.1890   0.0030 0.0030 1000

Quantiles
──────────────────────────────────────────────────
parameters
        2.5%     25.0%    50.0%    75.0%    97.5% 
alpha 154.0960 154.4158 154.5960 154.7652 155.1250
 beta   0.8206   0.8765   0.9056   0.9345   0.9911
sigma   4.7506   4.9671   5.0979   5.2220   5.4683


julia> quantile(Array(chns[:sigma]), [0.025, 0.25, 0.5, 0.75, 0.975])
5-element Array{Float64,1}:
 4.7505992500000005
 4.967145          
 5.097885          
 5.2220200000000006
 5.468349750000001 

julia> quantile(Array(chns[:beta]), [0.025, 0.25, 0.5, 0.75, 0.975])
5-element Array{Float64,1}:
 0.8205901999999999
 0.8764730000000001
 0.905634          
 0.93445225        
 0.99108425        

julia> quantile(Array(chns[:alpha]), [0.025, 0.25, 0.5, 0.75, 0.975])
5-element Array{Float64,1}:
 154.095975        
 154.41575         
 154.596           
 154.76524999999998
 155.125025        
```
which look spot on. The question is what is the intention of:
```
        vals = Array(hcat([quantile(collect(skipmissing(c.value[:,i,:])), w) for i in names(c)]...)')
```
is, but it looks suspicious to me.

**Comment by cpfiffer** [comment]
```
vals = Array(hcat([quantile(collect(skipmissing(c.value[:,i,:])), w) for i in names(c)]...)')
```
This was some weird holdover from the old MCMCChains that I hadn't gotten around to simplifying. I think we should probably replace this with just `Array(c)` and skirt around all that craziness. I can open a PR when I get home this evening.

> I really don't understand what the old (commented out) values of w do, but if I replace it by the w = [0.025, 0.25, 0.5, 0.75, 0.975] (now w == q), I get:

I think that was just a typo on my part when I was moving this stuff around. I think it may be a good idea to add some numerical correctness tests to summary stat functions to make sure that they're actually correct.

**Comment by goedman** [comment]
Definitely, we're both struggling with a `non-native` code base. Luckily you've made huge progress to make it much more useful. No doubt we will run into more of these surprises thanks to folks like Jeff and Chris using MCMCChains and taking the time to find these kind of bugs and point out shortcomings.

**Comment by goedman** [comment]
Cameron, I wonder if this fix is always correct. Now w is fixed and does not get updated from q in the argument list. Is w really necessary or could we just use q?

**Comment by cpfiffer** [comment]
Yet another one of those fun mistakes. You are correct, w is totally useless and q should be the correct parameter. I'll fix that.

**Comment by goedman** [comment]
As I mentioned, I really did not get the `vals = ...`. If there is a missing entry in one of the parameters wouldn't that section fail as the column lengths are now unequal?

I think summarize() is also pretty solid, I'll go over the discussion once more what is and what is not covered yet. I believe the `sections` keyword usage is the main item.

**Comment by cpfiffer** [comment]
> As I mentioned, I really did not get the `vals = ....` If there is a missing entry in one of the parameters wouldn't that section fail as the column lengths are now unequal?

It's one of those stupid things that I don't particularly want to mess with now since `missing` values are currently not really that prevalent in Turing (I don't know about the Stanverse). Plus, wouldn't the entire parameter would have to be `missing` for this to have an impact on how many `vals` were returned?

Either way, I'd like for this whole thing to go away with the switchover to `DataFrames` for chain summaries, so when I get to the `quantiles` function I'll make all this nice and tidy.

**Comment by goedman** [comment]
Hmmm,
```
skipmissing(itr)

  Return an iterator over the elements in itr skipping missing values. The returned
  object can be indexed using indices of itr if the latter is indexable. Indices
  corresponding to missing values are not valid: they are skipped by keys and
  eachindex, and a MissingException is thrown when trying to use them.
```
But I'm 100% with you, let's not tackle that right now.
