### ISSUE TITLE
Export hpd and/or add to summary

### ISSUE THREAD

**Issue by fisherc2** [TuringLang/MCMCChains.jl#80]
Hello-
In many fields, highest posterior density ([hpd](https://github.com/TuringLang/MCMCChains.jl/blob/75185f67169f2d84237798c4bb332cfcac302679/src/stats.jl#L185-L195)) is used instead of quantiles. hpd defines the smallest interval that contains x% of the posterior distribution.  Both statistics are similar for symmetric, unimodal distributions, but can differ quite a bit in other cases. Some users might find this feature to be useful.

**Comment by cpfiffer** [comment]
Closed by #82
