### ISSUE TITLE
Make density and mixeddensity unique

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/MCMCChains.jl#81]
Hi all-

As far as I can tell,  `density` and `mixeddensity` generate the same plot. It might be useful to change the function of `mixeddensity` to be a mixture of each chain. In other words, all of the samples would be pooled into one array and plotted. I think plotting individual chains is helpful for diagnostics and pooling is useful for generating uncluttered plots for publication.

**Comment by mkborregaard** [comment]
`mixeddensity` allows showing a histogram when chains are discrete.

**Comment by fisherc2** [comment]
Thanks for the info. In that case, I wonder if something like` :pooleddensity` would be useful. If not, I think we can close this issue.

**Comment by cpfiffer** [comment]
Currently I believe what you're talking about exists. Try `plot(chn, colordim = :parameter)` to plot pooled densities. Does this do what you've asking about?

**Comment by goedman** [comment]
Doesn't just `plot(chn)` provide that?

**Comment by cpfiffer** [comment]
`plot(chn)` gives you a plot for each parameter with all chains plotting for the same parameter, while `plot(chn, colordim=:parameter)` gives you one plot per chain and throws all the parameters on that one plot. The README has this example:

Summarize parameters | Summarize chains
:-------------------------:|:-------------------------:
`plot(chn; colordim = :chain)` | `plot(chn; colordim = :parameter)`
![p1](https://user-images.githubusercontent.com/7974003/45822242-f0009180-bce2-11e8-8fa0-a97c8732400f.png)  |  ![p2](https://user-images.githubusercontent.com/7974003/45822249-f131be80-bce2-11e8-8dd3-42db7d58abd9.png)

**Comment by fisherc2** [comment]
Just to clarify my initial post, I would like to do something that is similar to `density(chn[:Param1].value[:])` while maintaining the labels and settings that are used in the builtin plot functions. This would pool the samples across chains for a given parameter. As far as I can tell, none of the options discussed so far have this functionality.

**Comment by cpfiffer** [comment]
Oh, try indexing the chain first if you only want one parameter. `plot(chn[:Param1], colordim=:parameter)`. I think it's possible that `plot(chn, :Param1, colordim=:parameter)` might also work, but I'm not at a good machine to test that out right now.

**Comment by fisherc2** [comment]
Unfortunately, that does not work. It generates a subplot for each chain. Here is a simple example based on the Turing docs:


```
using Distributed,StatsPlots
addprocs(4)
@everywhere using Turing, Random

@everywhere @model gdemo(x) = begin
    s ~ InverseGamma(2,3)
    m ~ Normal(0, sqrt(s))
    for i in eachindex(x)
        x[i] ~ Normal(m, sqrt(s))
    end
end

num_chains = 4
sampler = NUTS(1000, 0.65)
model = gdemo([1.2, 3.5])

chns = reduce(chainscat, pmap(x->sample(model,sampler),1:num_chains))
plot(chns[:m], colordim=:parameter)
```
The other issue is that there is no way to generate this type of plot for all parameters. For example, `plot(chn,seriestype=:pooleddensity)`

**Comment by cpfiffer** [comment]
I guess I'm maybe not sure exactly what type of graph you're looking for. Here's the plotting output from the above code:

Overlay all the chains on top of eachother, with a plot per parameter:

```julia
density(chns[:m])
```
![1](https://user-images.githubusercontent.com/422990/55901308-f1f64900-5b7d-11e9-8782-02299fdad849.png)

```julia
# As above, but for all parameters.
density(chns)
```
![2](https://user-images.githubusercontent.com/422990/55901358-0b979080-5b7e-11e9-8ce1-838565e05fbc.png)

Overlay all parameters per chain together:

```julia
density(chns, colordim=:parameter, legend=true)
```

![3](https://user-images.githubusercontent.com/422990/55901391-18b47f80-5b7e-11e9-8042-28cd4f63b579.png)

Which one of the above provides the functionality you'd like to see in `mixeddensity`?

**Comment by fisherc2** [comment]
Sorry. Its clear to me now that I should have provided a more explicit example. I was thinking that something like  `plot(chn,seriestype=:pooleddensity)` would be equivalent to 


```
chns = reduce(chainscat, pmap(x->sample(model,sampler),1:num_chains))
p1 = density(chns[:m].value[:], title="m",ylabel="Density",xlabel="Sample value",leg=false)
p2 = density(chns[:s].value[:], title="s",ylabel="Density",xlabel="Sample value",leg=false)
p = plot(p1,p2,layout=(2,1))
```

The basic idea is that you can make smoother density plots by pooling the chain samples for a given parameter. 

![example](https://user-images.githubusercontent.com/9677184/55902928-722aa780-5b9a-11e9-868b-931dd86518c9.png)

**Comment by cpfiffer** [comment]
Ah, I understand now. I think I can put that in for you.

**Comment by fisherc2** [comment]
Thanks and sorry again for the confusion. I'll provide better examples in the future.

**Comment by goedman** [comment]
Another way of doing this is using the DataFrame route:
```
...
chns = reduce(chainscat, pmap(x->sample(model,sampler),1:num_chains))
df = DataFrame(chns, [:parameters])
p = Vector{Plots.Plot{Plots.GRBackend}}(undef, size(df, 2))
for (i, par) in enumerate(names(df))
  p[i] =density(df[par], lab="$par", xlab="Sample value", ylab="Density")
end
plot(p..., layout=(size(df, 2),1))
```

**Comment by cpfiffer** [comment]
> Thanks and sorry again for the confusion. I'll provide better examples in the future.

No problem! I'm glad we got this. I'll try and get this in this weekend. Does anyone have an issue with me adding a new keyword to the `plot` functions called `append_chains` which concatenates the chains together? I only say `append_chains` as the keyword since that's the convention in #79.

**Comment by itsdfish** [comment]
Since `pooleddensity` has been added, I'll go ahead and close this issue.
