### ISSUE TITLE
Calculation of Effective Sample Size for multiple chains

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/MCMCChains.jl#85]
Hi-

A few months ago, Rob and I had a brief discussion about effective sample size calculations for multiple chains. Currently, the maximum ESS is N, where N is the number of samples in a single chain. Why is this problematic? Consider the situation in which M chains consist of N samples each. The current metric does not distinguish between two extreme cases: (1) ESS for each chain is N/M and (2) ESS for each chain is N. In both cases, the combined ESS = N.

As a person with only cursory knowledge of ESS, my naive proposal is to switch to the formula used in [Stan](https://mc-stan.org/docs/2_18/reference-manual/effective-sample-size-section.html). As far as I can tell, the range of ESS is 0 to N*M, which seems desirable to me. I was wondering about the opinion of others.

**Comment by cpfiffer** [comment]
You're right that our calculation of ESS is nonideal. We've actually fixed this in the PR #79, which moves us over to Stan's formula. Whenever that goes through you'll see much a more reasonable ESS.

**Comment by itsdfish** [comment]
Thanks for the info. I'll close this issue in that case.
