### ISSUE TITLE
Consider new ideas on split-R, etc.

### ISSUE THREAD

**Issue by goedman** [TuringLang/MCMCChains.jl#86]
E.g. as described in https://arxiv.org/abs/1903.08008.

**Comment by cpfiffer** [comment]
I have an updated version of the ESS (split chain only, not the fancy new kind) calculation, but I'm not sure if it's right.

Using the Bernoulli model from Turing:

```julia
using Turing, MCMCChains

@model bermodel(y) = begin
    theta ~ Beta(1,1)
    for n = 1:length(y)
        y[n] ~ Bernoulli(theta)
    end
end

chn = mapreduce(x->sample(bermodel([0,1,0,0,0,0,0,0,0,1]), NUTS(2000, 1000, 0.65)), chainscat, 1:4)
```

I get the following estimate of the whole chain (including warmup samples):

```julia
julia> MCMCChains.ess(chn[:,:,:])
```
```julia
ESS

│ Row │ parameters │ ess    │ r_hat    │
│     │ Symbol     │ Any    │ Any      │
├─────┼────────────┼────────┼──────────┤
│ 1   │ theta      │ 1722.2 │ 0.999502 │
```

And without the warmup samples:

```julia
julia> MCMCChains.ess(chn[1001:2000,:,:])
```
```julia
ESS

│ Row │ parameters │ ess     │ r_hat    │
│     │ Symbol     │ Any     │ Any      │
├─────┼────────────┼─────────┼──────────┤
│ 1   │ theta      │ 575.058 │ 0.999004 │
```

I've compared this to Stan using this model:

```stan
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  theta ~ beta(1,1);
  for (n in 1:N) 
    y[n] ~ bernoulli(theta);
}
```

Which gives me the following estimates:

```
Inference for Stan model: bernoulli.
4 chains, each with iter=2000; warmup=1000; thin=1; 
post-warmup draws per chain=1000, total post-warmup draws=4000.

       mean se_mean   sd  2.5%   25%   50%   75% 97.5% n_eff Rhat
theta  0.25    0.00 0.12  0.06  0.16  0.23  0.32  0.53  1397    1
lp__  -7.27    0.02 0.76 -9.52 -7.41 -6.97 -6.80 -6.75  1609    1

Samples were drawn using NUTS(diag_e) at Sat Apr 27 07:00:24 2019.
For each parameter, n_eff is a crude measure of effective sample size,
and Rhat is the potential scale reduction factor on split chains (at 
convergence, Rhat=1).
```

I'm not quite certain why I'm getting this difference. I'm pretty sure that Stan discards the warmup samples and I'm nowhere near that calculation when I do the same. The code's available on the `csp/ess-fix` branch. I'm following the original implementation for ESS and Rhat found in appendix A of the [article you linked above](https://arxiv.org/pdf/1903.08008.pdf).

**Comment by goedman** [comment]
Hi Cameron, I'm currently on Turks & Caicos Islands so will be a bit slow in responding and can't spend too much time. Will be back next Friday.

Like you, I tried it with:
```
using CmdStan, StatsPlots, Random

Random.seed!(12395391)

ProjDir = @__DIR__
cd(ProjDir)

berstanmodel = "
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  theta ~ beta(1,1);
  for (n in 1:N) 
    y[n] ~ bernoulli(theta);
}
"

data = Dict("y" => [0,1,0,0,0,0,0,0,0,1],
  "N" => 10)

stanmodel = Stanmodel(
   name = "berstanmodel", model = berstanmodel, nchains = 4);
   
@time rc, chns, cnames = stan(stanmodel,
   data, summary=true, ProjDir);

describe(chns)

MCMCChains.ess(chns)
```

I expect repeated runs to be pretty close but not identical. Running this script a number of times the shows a very similar variation.

I'm a bit confused by the Turing results where too often I see an ess > draws (samples after warmup).

I'll try to do a comparison with the ess version in DynamicHMC.

**Comment by goedman** [comment]
For Turing I used:
```
using Turing, MCMCChains, StatsPlots, Random

#Random.seed!(1237591)

@model bermodel(y) = begin
    theta ~ Beta(1,1)
    for n = 1:length(y)
        y[n] ~ Bernoulli(theta)
    end
end

chn = mapreduce(x->sample(bermodel([0,1,0,0,0,0,0,0,0,1]),
  NUTS(3000, 1000, 0.65)), chainscat, 1:4)

describe(chn[1001:3000,:,:])
```

**Comment by goedman** [comment]
Oops, forgot I doubled the number of samples in Turing.

Running 100 simulations of drawing 4 x 1000 samples::

Turing:  mean=1349.1653644107696  std=334.508834524877 (target accept ratio=0.65)
Turing:  mean=1262.3685573846797 std=379.9902742044083 (target accept ratio=0.85)
CmdStan: mean=  1476.8725895863847 std=131.58115911039977 (mean accept stat = 0.92)
DynamicHMC: mean=1413.6549978357848 std=155.33584435271422

Food for thought! In attached pdf 1=cmdstan, 2=Turing, 3=dHMC.

[ess estimates.pdf](https://github.com/TuringLang/MCMCChains.jl/files/3124480/ess.estimates.pdf)

**Comment by goedman** [comment]
A slightly better figure (this time with the Turing target accept stat set to 0.95).

[ess_estimates_plot.pdf](https://github.com/TuringLang/MCMCChains.jl/files/3125246/ess_estimates_plot.pdf)

**Comment by goedman** [comment]
This is the test program:
```
using CmdStan, Turing, StatsPlots, Random, MCMCDiagnostics

Random.seed!(12395391)

ProjDir = @__DIR__
cd(ProjDir)

berstanmodel = "
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  theta ~ beta(1,1);
  for (n in 1:N) 
    y[n] ~ bernoulli(theta);
}
"

data = Dict("y" => [0,1,0,0,0,0,0,0,0,1],
  "N" => 10)

stanmodel = Stanmodel(
   name = "berstanmodel", model = berstanmodel, nchains = 4);


@model bermodel(y) = begin
    theta ~ Beta(1,1)
    for n = 1:length(y)
        y[n] ~ Bernoulli(theta)
    end
end

ess_array_turing = []
ess_array_cmdstan = []
ess_array_dHMC_cmdstan = []
ess_array_dHMC_turing = []

for i in 1:100
  chn = mapreduce(x->sample(bermodel([0,1,0,0,0,0,0,0,0,1]),
    NUTS(2000, 1000, 0.95)), chainscat, 1:4)
  dft = describe(chn[1001:2000,:,:])[1]
  append!(ess_array_turing, dft[:theta, :ess])
  rc, chns, cnames = stan(stanmodel,
     data, summary=true, ProjDir);
  dfc = describe(chns)[1]
  append!(ess_array_cmdstan, dfc[:theta, :ess])
  
  ac = Array(chns);
  at = Array(chn[1001:2000,:,:]);
  append!(ess_array_dHMC_cmdstan, effective_sample_size(ac))
  append!(ess_array_dHMC_turing, effective_sample_size(at))
end

[mean(ess_array_turing), std(ess_array_turing)] |> display
[mean(ess_array_cmdstan), std(ess_array_cmdstan)] |> display
[mean(ess_array_dHMC_turing), std(ess_array_dHMC_turing)] |> display
[mean(ess_array_dHMC_cmdstan), std(ess_array_dHMC_cmdstan)] |> display

p = Array{Plots.Plot{Plots.GRBackend}}(undef, 3);
p[1] = plot(ess_array_cmdstan, lab="MCMCChains/CmdStan", xlim=(0, 170))
p[1] = plot!(ess_array_dHMC_cmdstan, lab="dHMC/CmdStan")
p[1] = plot!(ess_array_turing, lab="MCMCChains/Turing")
p[1] = plot!(ess_array_dHMC_turing, lab="dHMC/Turing")
p[2] = plot(ess_array_cmdstan, lab="MCMCChains/CmdStan", xlim=(0, 170))
p[2] = plot!(ess_array_dHMC_cmdstan, lab="dHMC/CmdStan")
p[3] = plot(ess_array_turing, lab="MCMCChains/Turing", xlim=(0, 170))
p[3] = plot!(ess_array_dHMC_turing, lab="dHMC/Turing")
plot(p..., layout=(3,1))
savefig("ess_estimates_plot.pdf")
```

**Comment by cpfiffer** [comment]
That actually seems pretty reasonable! I'm much more pleased with the outcome after seeing your simulations.

**Comment by goedman** [comment]
Yip, maybe some variation in how autocor is computed.

**Comment by cpfiffer** [comment]
Should I tidy this up and get a PR out? Afterwards I can can work on the rank normalized/folded ESS and R hat values.

**Comment by goedman** [comment]
I would think so, this is much better than just inserting the number of draws. Mitzi (from the Stan development team) explained to me how I can store the summary cmdstan print out so I will include those results when back in DC. ESS is rather crude I believe, but does give an indication the results contain enough draws.

**Comment by goedman** [comment]
Just for completeness, this plot also shows the actual N_Eff as reported by Stan's stansummary (labeled as CmdStan).


[ess_estimates_plot.pdf](https://github.com/TuringLang/MCMCChains.jl/files/3134491/ess_estimates_plot.pdf)
