### ISSUE TITLE
Further steps on describe()

### ISSUE THREAD

**Issue by goedman** [TuringLang/MCMCChains.jl#87]
- [ ] Should `describe()` return a df or split this between show/describe or describe/summarize (as it is now). If we choose the second option I have a slight preference for keeping describe/summarize.

- [ ] Right now `describe(c, sections=[:internals])` returns the :parameters section, while `summarize(c, sections=[:internals]) returns the :internals.

**Comment by cpfiffer** [comment]
On the first point, I think I'm leaning towards having `describe` return the `ChainDataFrame`s with no printing involved, and setting the default `show` function to print out the results of the `describe` function. I think this will get a lot of stuff out of the way and maybe be a little more straightforward to use.

The second point's a bug which needs to be fixed, duly noted!

**Comment by goedman** [comment]
Sounds fine.

Yes, so many parts have changed, I'm sure not all is yet covered by the tests!

**Comment by goedman** [comment]
Hi Cameron, 

have you looked into above bug? If not, I would like to take a look as it is a problem for me in my StatisticalRethinking work.

**Comment by cpfiffer** [comment]
Sorry, slipped my mind over the weekend. Thank you for the reminder! #94 addresses everything in this issue.

**Comment by cpfiffer** [comment]
@JuliaRegistrator `register()`

**Comment by cpfiffer** [comment]
@JuliaRegistrator `register()`
