### ISSUE TITLE
Register version 0.3.7 through new system

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/MCMCChains.jl#88]
Hi-

As discussed [here](https://discourse.julialang.org/t/package-wont-update-to-most-recent-version/23197/8), the newest release is not registered through new new system and does not show up via `]update` as a result.

**Comment by cpfiffer** [comment]
Yeah, that's my bad. The version number was wrong on the Project.toml file and the PR to METADETA fell through before Attobot shut down. I'm getting us all set up to publish with Registrator now, but thank you for bringing this to our attention!

**Comment by cpfiffer** [comment]
Could you try updating to 0.3.7 on your side now? We've got this up and running on General and I want to make sure it's working.

**Comment by itsdfish** [comment]
No problem. 

Unfortunately, it still is not working for me. Is there something I should try aside from `]update `?

**Comment by goedman** [comment]
What does `] st MCMCChains` return?

**Comment by itsdfish** [comment]
Here is what I get:

```
(v1.1) pkg> update
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.1/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.1/Manifest.toml`
 [no changes]

(v1.1) pkg> st
    Status `~/.julia/environments/v1.1/Project.toml`
  [c095b0ea] ACTRModels v0.1.0 [`~/.julia/dev/ACTRModels`]
  [04872c7e] ACTRTutorial v0.1.0 [`~/.julia/dev/ACTRTutorial`]
  [c52e3926] Atom v0.8.5
  [a93c6f00] DataFrames v0.17.1
  [39dd38d3] Dierckx v0.4.1
  [31c24e10] Distributions v0.18.0
  [aca21b3a] FFTDist v0.1.0 [`~/.julia/dev/FFTDist`]
  [7073ff75] IJulia v1.18.1
  [e5e0dc1b] Juno v0.7.0
  [c7f686f2] MCMCChains v0.3.6
  [ea88e8cf] MathPsychACTR v0.1.0 [`~/.julia/dev/MathPsychACTR`]
  [429524aa] Optim v0.18.1
  [d96e819e] Parameters v0.10.3
  [91a5bcdd] Plots v0.24.0
  [1fd47b50] QuadGK v2.0.3
  [295af30f] Revise v2.1.2
  [2913bbd2] StatsBase v0.29.0
  [4c63d2b9] StatsFuns v0.8.0
  [f3b207a7] StatsPlots v0.10.2
  [fce5fe82] Turing v0.6.14

(v1.1) pkg> 
```

**Comment by cpfiffer** [comment]
Try now. I ran `]add MCMCChains` on my work machine (which doesn't have it installed) and it seems it's working.

**Comment by itsdfish** [comment]
I eventually got it to work after deleting the .julia folder. I'm not sure why it did not work with a simple ]update. I'm not sure exactly how the package system works. Perhaps there were residual files from the old system that were interfering. In either case, it works now. Thanks!

**Comment by cpfiffer** [comment]
Strange. Well, works now I guess. Thanks for bringing this one up.

**Comment by benelsen** [comment]
I just checked and it didn't update MCMCChains for me either. 
I dug around a bit and Turing might be holding back 0.3.7 for some reason. Here's the [Compat.toml](https://github.com/JuliaRegistries/General/blob/master/T/Turing/Compat.toml#L70) which for some reason adds an upper bound for MCMCChains.

**Comment by itsdfish** [comment]
I think benelsen is right. When I initially deleted .julia, installed MCMCChains and then Turing, which worked. However, it does not work in the reverse order.

**Comment by cpfiffer** [comment]
Okay, give it a shot again. We just released a version of Turing with a higher cap on MCMCChains.

**Comment by itsdfish** [comment]
It works now. Hooray!

Thanks!
