### ISSUE TITLE
Register v0.3.7

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/MCMCChains.jl#89]
@JuliaRegistrator register()

**Comment by goedman** [comment]
@JuliaRegistrator `register()`

**Comment by cpfiffer** [comment]
Ah, I'll update that.

**Comment by cpfiffer** [comment]
@JuliaRegistrator `register()`

**Comment by goedman** [comment]
I'm not sure if this will suffice. Is the existing tag 0.3.7 in sync with master? Maybe skip to 0.3.8 if this fails or uses the old tagged version?

**Comment by cpfiffer** [comment]
Yeah, the last published was 0.3.6.

**Comment by cpfiffer** [comment]
0.3.7 was never published before, so this will amend that. The only thing out of date is the tag.

**Comment by cpfiffer** [comment]
Looks like this was merged on General. That was actually a pretty painless changeover.

**Comment by goedman** [comment]
Yes, it was. I'm a bit worried about the `53 commits` message that remains visible under Releases, but these definitely seem to be included. I guess that will be corrected if 0.3.8 is released at some point in the future and a new tag is created.
