### ISSUE TITLE
ESS appears to be incorrect

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/MCMCChains.jl#90]
I noticed two problems with ESS. First, it appears to always be ESS=Nsamples. Second, when I  excluded the warmup samples, ESS=0. Here is a simple example:

```
using Turing, StatsPlots, Random

Random.seed!(14)
data = rand(Normal(0,1), 30)

@model model(y) = begin
    μ ~ Normal(0, 10)
    N = length(y)
    for n in 1:N
        y[n] ~ Normal(μ,1)
    end
end;

# Settings of the NUTS sampler.
Nsamples = 2000
#Target acceptance rate
δ = .8
#The number of adaption or warmup samples
Nadapt = 1000
#Collects sampler configuration options
specs = NUTS(Nsamples,Nadapt,δ)

# Start sampling.
chain = sample(model(data),specs);

plot(chain,seriestype=(:autocorplot))

#Produces ESS = 0
subset = chain[(Nadapt+1):end,:,:]
```
Autocorrelation is good but it ESS should be less than Nsamples.

**Comment by cpfiffer** [comment]
I can replicate this. Not sure exactly what's going on here. I suspect a 0 is being multiplied through in somewhere in the calculations.

**Comment by itsdfish** [comment]
By the way, I wonder if the information in this [blog post](https://www.juliabloggers.com/sampling-variation-in-effective-sample-size-estimates-mcmc/) might be useful for designing a unit test for ESS. There appears to be a relationship between ESS and an autoregressive process.

**Comment by goedman** [comment]
Let’s continue this discussion in #86 which it a slightly longer term goal but possibly with intermediate steps.
